<style>
body {font-family:Arial,Helvetica,sans-serif; font-size:12px; color:#000000; text-decoration:none;}
A.body {font-family:Arial,Helvetica,sans-serif; font-size:12px; color:#000000; text-decoration:underline;}
A.body:hover {color:Red; text-decoration:underline;}
A.body:active {color:Red;}
A.body:visited {color:#000000;}
A.body:visited:hover {color:Red; text-decoration:underline;}

.big {font-family:Arial,Helvetica,sans-serif; font-size:14px; color:#000000; text-decoration:none;}
A.big {font-family:Arial,Helvetica,sans-serif; font-size:14px; color:#000000; text-decoration:none;}
A.big:hover {color:Red; text-decoration:underline;}
A.big:active {color:Red;}
A.big:visited {color:#000000;}
A.big:visited:hover {color:Red; text-decoration:underline;}
</style>

<strong class="big">1) TERMS APPLICABLE TO NATION GSM PLANS:</strong>

<p><strong>Credit approval required.</strong> Subscriber must live and have a mailing address within Cingular's owned network coverage area. An early termination fee of $175 applies if service is terminated before the end of the contract term. If phone is returned within 3 days, activation fee will be refunded. If phone is returned within 30 days in like-new condition with all components, early termination fee will be waived. All other charges apply. Some dealers impose additional fees.</p>

<p><strong>Minute Increment Billing and Usage:</strong> Airtime and other measured usage are billed in full-minute increments, and actual airtime and usage are rounded up to the next full increment at the end of each call for billing purposes. Cingular charges a full-minute increment of usage for every fraction of the last minute used on each wireless call. Minutes will be depleted according to usage in the following order: Night and Weekend Minutes, Mobile to Mobile Minutes, Anytime Minutes and Rollover&reg; Minutes . Calls placed on networks served by other carriers may take longer to be processed, and billing for these calls may be delayed. Those minutes will be applied against your Anytime monthly minutes in the month in which the calls appear on your bill. Unanswered outgoing calls of 30 seconds or longer incur airtime. You may obtain usage information by calling customer service or using one of our automated systems.</p>

<p><strong>Pricing/Taxes/No Proration:</strong> Final month's charges are not prorated. Prices are subject to change. Prices do not include taxes. <strong>Activation Fees: $36</strong> Activation Fee for each new line.</p>

<p><strong>Nights and Weekends:</strong> Nights are 9:00 p.m. to 6:00 a.m. Weekends are 9:00 p.m. Friday to 6:00 a.m. Monday (based on time of day at switch providing your service). Included long distance calls can be made from the 50 United States, Puerto Rico and U.S. Virgin Islands to the 50 United States, Puerto Rico, U.S. Virgin Islands, Guam and Northern Mariana Islands. Roaming charges do not apply when roaming within the service area of land-based networks of the 50 United States, Puerto Rico and U.S. Virgin Islands. International long distance rates vary. Additional charges apply to services used outside the land borders of the U.S., Puerto Rico and U.S. Virgin Islands.</p>

<p><strong>Unlimited Voice Services:</strong> Unlimited voice services are provided solely for live dialog between two individuals. Unlimited voice services may not be used for conference calling, call forwarding, monitoring services, data transmissions, transmission of broadcasts, transmission of recorded material, or other connections that do not consist of uninterrupted live dialog between two individuals. If Cingular finds that you are using an unlimited voice service offering for other than live dialog between two individuals, Cingular may at its option terminate your service or change your plan to one with no unlimited usage components. Cingular will provide notice that it intends to take any of the above actions, and you may terminate the agreement.</p>

<p><strong>Off-net Usage:</strong> If your minutes of use (including unlimited services) on other carrier networks (&quot;off-net usage&quot;) during any two consecutive months exceeds your off-net usage allowance, Cingular may at its option terminate your service, deny your continued use of other carriers' coverage, or change your plan to one imposing usage charges for off-net usage. Your off-net usage allowance is equal to the lesser of 750 minutes or 40% of the Anytime Minutes included with your plan. Cingular will provide notice that it intends to take any of the above actions, and you may terminate the agreement.</p>

<p><strong>Caller ID Blocking:</strong> Your billing name may be displayed along with your wireless number on outbound calls to other wireless and landline phones with Caller ID capability. Contact customer service for information on blocking the display of your name and number. You may be charged for both an incoming and an outgoing call when incoming calls are routed to voicemail, even if no message is left. See Wireless Service Agreement for additional conditions and restrictions.</p>

<p><strong>Rollover&reg; Minutes :</strong> Rollover&reg; Minutes accumulate and expire through 12 rolling bill periods. Bill Period 1 (activation) unused Anytime Minutes will not carry over. Bill Period 2 unused Anytime Minutes will begin to carry over. Rollover&reg; Minutes accumulated starting with Bill Period 2 will expire each bill period as they reach a 12 bill period age. Rollover&reg; Minutes will also expire immediately upon default or if customer changes to a non-Rollover&reg; plan. If you change plans (including the formation of a FamilyTalk plan), or if an existing subscriber joins your existing FamilyTalk plan, any accumulated Rollover&reg; Minutes in excess of your new plan or the primary FamilyTalk line's included Anytime Minutes will expire. Rollover&reg; Minutes are not redeemable for cash or credit and are not transferable.</p>

<p><strong>Mobile to Mobile Minutes:</strong> Mobile to Mobile Minutes may be used, subject to the above provisions governing unlimited usage, when directly dialing or receiving calls from any other Cingular phone number from within your calling area. Mobile to Mobile Minutes may not be used for interconnection to other networks. Calls to Cingular Voicemail and return calls from Voicemail not included.</p>
	
<br>
	
<strong class="big">2) WIRELESS DATA SERVICE TERMS AND CONDITIONS</strong>

<p><strong class="bodyBlack">I. General Terms And Conditions Applicable To Cingular Data Services, Including But Not
Limited To, Features That May Be Used With Data Services And Wireless Content.</strong></p>

<p>Cingular provides data services, including but not limited to, features that may be used with data services and wireless content (&quot;Services&quot;). These Services may be subject to credit approval and may only be available with certain rate plans. An activation fee of up to $36 may apply to each new line. Compatible data-enabled wireless device required.</p>

<p><strong>Usage/Billing:</strong> Usage and monthly fees will be charged as specified in your plan. Data transport is billed in full-kilobyte increments, and actual transport is rounded up To the next full-kilobyte increment at the end of each data session for billing purposes. Cingular charges a full kilobyte of data transport for every fraction of the last kilobyte of Data transport used on each data session. Network overhead, software update requests, and Resend requests caused by network errors can increase measured kilobytes. Airtime and other Measured usage are billed in full-minute increments and rounded up to the next full-minute Increment at the end of each call for billing purposes. Data sent and received includes, but is not limited to downloads, email, overhead and software update checks. Unless designated for International or Canada use, prices and unlimited use apply to EDGE/GPRS and BroadbandConnect (if applicable) access and use on the Cingular network and its partner networks within the United States and its territories (Puerto Rico and the U.S. Virgin Islands), excluding areas within the Gulf of Mexico. Charges will be based on the location of the site receiving and transmitting service and not the location of the subscriber. Data plans include BroadBandConnect access (where available in metropolitan markets) when activated on a compatible, eligible 3G device (subject to availability). There are 1024 kilobytes in a megabyte. Overage is billed by the kilobyte. Service charges paid in advance for annual Services are nonrefundable. Some Services may require an additional monthly subscription fee and/or be subject to additional charges and restrictions. See applicable Service materials for complete pricing and terms. Prices do not include taxes, directory assistance, roaming, universal services fees or other exactions and are subject to change. You may obtain usage information by calling customer service or using one of our automated systems.</p>

<p><strong>Voice:</strong> If you have a voice-capable device, unless you request voice blocking, select a data plan that restricts voice access or select a qualified voice plan, the default rate for voice calls on the Cingular network are 40&cent; per minute and 69&cent; per minute for domestic roaming voice calls off the Cingular network (rates are subject to change without notice). Additional taxes and surcharges may apply. See Cingular Nation&reg; map at store or <a href="http://att.com/wireless" title="" class="body">att.com/wireless</a> for default voice coverage area. If you request voice blocking or your selected data plan restricts voice access, all voice calling capabilities (except for outgoing calls from the device to 911 or 611) will be blocked, including without limitation, calls from 911 or 611 to the device. If you have a voice plan, voice calls are billed as provided in your voice rate plan.</p>

<p><strong>Roaming:</strong> Roaming charges for data or voice service may be charged with some plans when outside the Cingular network. Display on your device will not indicate whether you will incur roaming charges. Services originated or received while outside your plan's included coverage area are subject to roaming charges. Use of Services when roaming is dependent upon roaming carrier's support of applicable network technology and functionality. Check with roaming carriers individually for support and coverage details. Billing for domestic and international roaming usage may be delayed up to three billing cycles due to reporting between carriers.</p>

<p><strong>International Roaming:</strong> See <a href="/learn/international/index.jsp" title="" class="body">wireless.att.com/learn/international/index.jsp</a> or dial 1-866-CINGULAR for more information and for a list of currently available countries and carriers. Compatible international-capable handheld required. Certain countries and/or carriers within a roaming zone may be unavailable with certain plans or Services while roaming. Availability, quality of coverage and Services while roaming are not guaranteed. Rates apply to Cingular customers only. Certain tenure, billing and credit restrictions and additional charges may apply.</p>

<p><strong>Cancellations/Early Termination Fee:</strong> An Early Termination Fee of <strong>$175</strong> may be assessed against you in the event that you terminate your Wireless Service Agreement and/or selected plan before the expiration of its term. You may cancel your service, for any reason and without incurring the Early Termination Fee, within thirty (30) days of signing your Wireless Service Agreement, PROVIDED, however, that if you cancel service you will remain responsible for any service fees and charges incurred. If you cancel within three (3) days of signing your Wireless Service Agreement, you will be entitled to a refund of your activation fee, if any. If you exercise this option, you may be required to return devices and associated accessories purchased in connection with your Wireless Service Agreement.</p>

<p><strong>Service Availability and Access/Coverage:</strong> Cingular does not guarantee availability of network. Services may be subject to certain equipment and compatibility/limitations including memory, storage, network availability, coverage, accessibility and data conversion limitations. Services (including without limitation, eligibility requirements, plans, pricing, features and/or service areas) are subject to change without notice. When outside coverage area, access will be limited to information and applications previously downloaded to or resident on your device. Coverage areas vary between Cingular BroadbandConnect, EDGE and GRPS. Cingular BroadbandConnect only available in select markets. See coverage map(s), available at store or from your sales representative, for details. Cingular BroadbandConnect download speeds only available on the Cingular BroadbandConnect network. Actual download speeds depend upon device characteristics, network, network availability and coverage levels, tasks, file characteristics, applications and other factors. Performance may be impacted by transmission limitations, terrain, in-building/in-vehicle use and capacity constraints.</p>

<p><strong>Information/Content:</strong> Certain information or content is provided by independently owned and operated content providers or service providers who are subject to change at any time without notice. Cingular is not a publisher of third-party information or content and is not responsible for any Opinions, advice, statements, or other information, services or goods provided by third Parties. Third-party content or service providers may impose additional charges. Policies regarding intellectual property, privacy and other policies may differ among Cingular's content or service providers and you are bound by such policies when you visit their respective sites or use their services. It is your responsibility to read the rules or service agreements of each content provider or service provider. Any information you involuntarily or voluntarily provide third parties is governed by their policies. The accuracy, appropriateness, content, completeness, timeliness, usefulness, security, safety, merchantability, fitness for a particular purpose, transmission or correct sequencing of any information or downloaded data is not guaranteed or warranted by Cingular or any content providers or other third party. Delays or omissions may occur. Neither Cingular nor its content providers, service providers or other third parties shall be liable to you for any loss or injury arising out of or caused, in whole or in part, by any information acquired through the Service. You acknowledge that every business or personal decision, to some degree or another, represents an assumption of risk, and that neither Cingular nor its content and service providers or suppliers, in providing access to information, underwrites, can underwrite, or assumes your risk in any manner whatsoever.</p>

<p><strong>Prohibited and Permissible Uses:</strong> Data Service sessions may be conducted only for the following purposes: (i) Internet browsing; (ii) email; and (iii) corporate intranet access (including access to corporate email, customer relationship management, sales force automation, and field service automation applications). Prohibited uses include, but are not Limited to, using services: (i) with server devices or with host computer applications, Including, without limitation, web camera posts or broadcasts, continuous jpeg file transfers, Automatic data feeds, telemetry applications, peer-to-peer (p2p) file sharing, automated Functions or any other machine-to-machine applications; (ii) as substitute or backup for Private lines or dedicated data connections; (iii) for voice over ip; (iv) in conjunction with Wwan or other applications or devices which aggregate usage from multiple sources prior to Transmission; (v) using the services for any activity that adversely affects the ability of Other people or systems to use either the services or other parties' internet-based resources Including, but not limited to excessive consumption of network or system resources (whether Intentional or unintentional) and &quot;denial of service&quot; (dos) attacks against another Network host or individual user; or (vi) interference with or disruption of other network Users, network services or network equipment. Except for content formatted in accordance with Cingular's content standards, unlimited plans cannot be used for uploading, downloading or Streaming of video content (e.g. movies, tv), music or games. Furthermore, unlimited plans (except for dataconnect and blackberry&reg; tethered) cannot be used for any applications that Tether the device (through use of, including without limitation, connection kits, other Phone/pda-to-computer accessories, bluetooth&reg; or any other wireless technology) to laptops, Pcs, or other equipment for any purpose. Service is not intended to provide full-time connections, and the Service may be discontinued after a significant period of inactivity or after sessions of excessive usage. Cingular reserves the right to (i) limit throughput or amount of data transferred, deny Service and/or terminate Service, without notice, to anyone it believes is using the Service in any manner prohibited above or whose usage adversely impacts its network or service levels or hinders access to its network and (ii) protect its network from harm, which may impact legitimate data flows. You may not send solicitations to Cingular subscribers without their consent. You may not use the Services other than as intended by Cingular and applicable law. Plans are for individual, non-commercial use only and are not for resale.</p>

<p><strong>Security:</strong> Cingular does not guarantee security. Data encryption is available with some, but not all, Services sold by Cingular. If you use your device to access company email or information, it is your responsibility to ensure your use complies with your company's internal IT and security procedures.</p>

<p><strong>Changes to the terms and conditions:</strong> These terms and conditions may be changed from time-to-time. Cingular will post the most current version of these terms and conditions on the MEdia Net web site (<a href="http://att.com/medianet" title="" class="body">att.com/medianet</a>) or other appropriate location. Please check these regularly to inform yourself about changes to the terms and conditions, policies, news, etc.</p>

<p><strong>Access Requirements:</strong> Additional hardware, software, subscription, credit or debit card, Internet access from your compatible PC and/or special network connection may be required and you are solely responsible for arranging for or obtaining all such requirements. Some solutions may require third party products and/or services, which are subject to any applicable third party terms and conditions and may require separate purchase from and/or agreement with the third party provider. Cingular is not responsible for any consequential damages caused in any way by the preceding hardware, software or other items/requirements for which you are responsible.</p>

<p><strong>Miscellaneous:</strong> Not all plans or Services are available for purchase or use in all sales channels, in all areas or with all devices. If your usage of the Services (including unlimited data and messaging plans) on other carrier's networks (&quot;offnet usage&quot;) during any two consecutive months exceeds your offnet usage allowance, Cingular may at its option terminate your wireless service or access to data Services, deny your continued use of other carriers' coverage, or change your plan to one imposing usage charges for offnet usage. Your offnet usage allowance is equal to the lesser of 6 megabytes or 20% of the kilobytes included with your plan, and for messaging plans the lesser of 3000 messages or 50% of the messages included with your plan. Cingular will provide notice that it intends to take any of the above actions and you may terminate your agreement. You may be required to (1) use a device programmed with Cingular's preferred roaming database; and (2) have a mailing address and live in the United States, Puerto Rico or the U.S. Virgin Islands. Cingular is not responsible for loss or disclosure of any sensitive information you transmit. Cingular Services are not equivalent to landline Internet. Cingular is not responsible for nonproprietary services or their effects on devices. If applicable, use of Desktop Toolbar requires compatible home computer products. Cingular reserves the right to Terminate your services with or without cause, including without limitation, upon expiration or Termination of your wireless service agreement. Caller ID blocking is not available when using the Services, and your wireless number is transmitted to Internet sites you visit. You may receive unsolicited messages from third parties as a result of visiting Internet sites, and a per-message charge may apply whether the message is read or unread, solicited or unsolicited.</p>

<p><strong>Additional Terms:</strong> See below for additional terms relating to specific Services. In addition, all use of the Cingular network and the Services is governed by Cingular's Acceptable Use Policy, which can be found at <a href="http://att.com/AcceptableUsePolicy" title="" class="body">att.com/AcceptableUsePolicy</a>, as determined solely by Cingular. Cingular can revise its Acceptable Use Policy at any time without notice by updating this posting. Use of the Services is subject to Terms and Conditions of your Wireless Service Agreement. See Wireless Service Agreement, <a href="http://att.com/wireless" title="" class="body">att.com/wireless</a> or Cingular Customer Service for additional conditions, restrictions, privacy policy and information.</p>

<p><strong>Intellectual Property:</strong> All trademarks, service marks and trade names used on or in connection with the Services are the property of their respective owners. You must respect the intellectual property rights of Cingular, our third-party content providers, and any other owner of intellectual property whose protected property may appear on any website and/or dialogue box controlled by Cingular or accessed through the Cingular's websites. Except for material in the public domain, all material displayed in association with the Service is copyrighted or trademarked. Except for personal, non-commercial use, trademarked and copyrighted material may not be copied, downloaded, redistributed or otherwise exploited, in whole or in part, without the permission of the owner. The GSM lettermark is a trademark of the GSM Association. The RIM and BlackBerry&reg; families of related marks, images and symbols are the exclusive properties and trademarks or registered trademarks of Research In Motion Limited - used by permission. Good, the Good logo and GoodLink are trademarks of Good Technology, Inc., in the United States and/or other countries. Good Technology, Inc., and its products and services are not related to, sponsored by or affiliated with Research In Motion Limited. AT&amp;T, AT&amp;T logo, Cingular and Cingular logos are trademarks of AT&amp;T Knowledge Ventures and/or AT&amp;T affiliated companies. &copy; 2007 AT&amp;T Knowledge Ventures. All rights
reserved.</p>

<br>

<p><strong class="bodyBlack">II. Additional Terms For Specific Data Services</strong></p>

<p><strong>Text, Instant Messaging and Picture/Video Messaging</strong><br>
Messages are limited to 160 characters per message. Premium text and picture/video messages are charged at their stated rates. Standard rates apply to all incoming messages when in the U.S. Different, non-standard per message charges apply to international messages sent from the U.S. Text, Instant, Picture, and Video messages are charged when sent or received, whether read or unread, solicited or unsolicited. Cingular does not guarantee delivery of messages. Text, Instant, Picture, and Video messages, including downloaded content, not delivered within 7 days will be deleted. Cingular reserves the right to change this delivery period as needed without notification. You are charged for each part of messages that are delivered to you in multiple parts. Picture/Video Messaging, data plan, and Text Messaging may need to be provisioned on an account in order to use Picture/Video Messaging. Some elements of Picture/Video messages may not be accessible, viewable, or heard due to limitations on certain wireless phones, PCs, or e-mail. Maximum Picture/Video message size is 300 kilobytes, although handset limitations might be lower. Cingular reserves the right to change the Picture/Video message size limit at any time without notification. Picture/Video Messaging pricing is for domestic messages only. When a single message is sent to multiple recipients, the sender is charged for one message for each recipient and each recipient is charged for the message received. Text message notifications may be sent to non-Picture/Video Messaging subscribers if they subscribe to Text Messaging.</p>

<p><strong>Unlimited Mobile to Mobile Messaging:</strong> Includes unlimited text, picture, and video messages between Cingular wireless customers sent or received while on the Cingular owned wireless network. Instant Messages and any other usage not expressly included herein will be debited from your package's messaging allowance. A subscription to one of the current Message Packages, MEdia Bundles or Max Bundles is required.</p>

<p><strong>DirectBill Service:</strong> DirectBill enables you to bill third party content or services on your wireless bill. Use of the DirectBill service constitutes consent to these terms and conditions. There is no charge for creating a Cingular DirectBill account and DirectBill is available to you automatically as a subscriber.</p>

<p><strong>Charges and Payment:</strong> You will be charged monthly on your Cingular wireless bill for all transactions entered into during the previous billing period using the DirectBill service. If you authorize others to use your payment information, you are liable for charges they incur. You have full-time access to your transaction history by logging into <a href="/db " title="" class="body">wireless.att.com/db</a> and selecting &quot;Review My Account.&quot; You may contest charges and seek refunds for purchases with which you are not satisfied. Cingular reserves the right to restrict the use of the Direct Bill service or terminate the account of anyone who seeks refunds on improper grounds or otherwise abuses the DirectBill service. Prepaid/GoPhone&reg; customers: Transactions will be debited from your account balance at the time of the transaction. If there are insufficient funds in your account at the time of the transaction, you will not be able to complete your purchase or receive the requested services.</p>

<p><strong>Ringtones/Graphics/Games/Cool Tools/Alerts</strong><br>
Actual ringtone, graphics, game or Cool Tools may vary based on the handset capabilities. Ringtones, graphics, games, Cool Tools, and alerts may be delivered in multiple messages. Ringtone, graphic, game, and Cool Tool charges are incurred at the stated one-time download rate or subscription rate, plus a kilobyte charge for the content transport when delivered. You will be charged each time you download ringtones, graphics, games, and Cool Tools. Usage charges apply to play multi-user games against other wireless users or the server.</p>

<p><strong>Cingular Sounds Tone Club</strong><br>
Your enrollment gives you the option to receive text messages each week on music trivia, news and more. Every 30 days your subscription will be automatically renewed and new credits added to your account which can be used to buy ringtones and graphics through the MEdia Mall. Music, Voice, Sound Effect Tones, polyphonic ringtones &amp; graphics are 1 credit. Unused credits expire at the end of each 30 day period. The 30 day period is not necessarily equivalent to a calendar month end or the billing cycle. You may terminate your subscription at any time by texting the word &quot;STOP&quot; to 7225. Any remaining credits will be available for the remainder of your subscription billing cycle. Savings claim based on price of Music Tones. Ringtone and graphics provided by independent providers.</p>

<p><strong>Mobile Email</strong><br>
Requires e-mail account with compatible internet service provider and a downloaded or preloaded e-mail application for the wireless device. Access and use of Mobile Email is billed by total volume of data sent and received (in kilobytes) in accordance with your MEdia Net service. E-mail attachments can not be sent, downloaded, read, or forwarded on the mobile device. Only a paper clip icon appears indicating an attachment. You must view attachments from your PC. Upgrades to the application may be required in order to continue to use the service. Wireless data usage charges will apply for downloading the application and any upgrades.</p>

<p><strong>Cingular Video</strong><br>
Not available in all areas and not available when off the Cingular-owned network. 3G phone and eligible data plan required. Depending on selected data plan, eligible voice plan may also be required. Monthly subscription to a package that includes unlimited data usage highly recommended. Customers not subscribed to a package that includes unlimited data usage will incur significant charges to view Cingular Video clips (&quot;CV&quot;). Video clips are not available for download. Cingular Video is charged at stated monthly subscription rates or at stated pay per view rates. Cingular Video provided by a monthly subscription rotates as appropriate for the service and is subject to withdrawal in the provider's sole discretion. Cingular Video provided on a pay per use basis can be viewed an unlimited number of times for 24 hours. Cingular Video is for individual use only and not for resale. No content may be captured or forwarded. Some Cingular Video content may be inappropriate for younger viewers. Parental guidance suggested. Use Parental Controls to restrict access to mature content. All screen images are simulated.</p>

<p><strong>$59.99 Data Connect Unlimited.</strong><br>
Requires two year agreement and subscription to eligible voice plan of $39.99 or higher maintained on same account. Limited to one per eligible voice line on qualified account.
Separate voice and data devices may be required.</p>

<p><strong>WI-FI CONNECT:</strong> Wi-Fi Connect available only with activation of an eligible DataConnect plan. Compatible Wi-Fi device with installation of Cingular Communication Manager software required to access Cingular Wi-Fi service. Wi-Fi Connect plans allow unlimited access (except as noted below) to Cingular Wi-Fi hotspots. Customers must pay applicable Wi-Fi access service fees directly to the Wi-Fi service provider for non-Cingular Wi-Fi hotspot usage. This agreement also can be viewed at <a href="http://att.com/laptopconnect" title="" class="body">att.com/laptopconnect</a>. Wireless 802.11b/g network interface card or a laptop/PDA enabled with 802.11 technology is required to access the Wi-Fi Service. Wi-Fi Service is not inherently secure. Cingular Wi-Fi Service is not part of the Cingular GSM<sup>TM</sup> /GPRS, EDGE or 3G networks and, therefore, does not have the encryption, authentication or other security features that may be available on those networks. Wireless communications can be intercepted by equipment and software designed for that purpose. Cingular strongly encourages and supports certain customer-provided security solutions, such as virtual private networks (VPNs), but does not provide these to its Wi-Fi users and is not responsible for their effectiveness. Wi-Fi Service is available only when it is within the operating range of the Cingular system or of an operator with which we have a roaming agreement. Wi-Fi Service access location lists and/or maps may be updated from time to time; actual service coverage, locations and quality may vary. To ensure that the Wi-Fi Service is not being used fraudulently, Cingular limits your usage of the Wi-Fi Service to 150 uses per month. If you do not use the Cingular Communication Manager software to connect to a Cingular network for 90 consecutive days, or if your license to use the software is otherwise terminated, you will not be able to access the Wi-Fi Service. Wi-Fi services requiring the use of credit card or other payment directly to the network provider are not part of Cingular's preferred network, if any, and additional charges will apply from the owner of such network.</p>

<p><strong>Additional Terms And Conditions&mdash;Global Plans:</strong> Available countries, coverage and participating international carriers included in the &quot;Select International Roam Zone&quot; vary from our generally available Canada/international data roam zones and may not be as extensive. The Select International Roam Zone is restricted to select international carrier(s). See <a href="http://att.com/dataconnectglobal" title="" class="body">att.com/dataconnectglobal</a> for a current list of participating carriers and eligible roam zones. Additional data usage in Select International Roam Zone is charged at: $0.005/KB. Standard international roaming rates apply to international data usage outside of the countries included in the Select International Roam Zone. Under this plan, with respect to the countries included in the Select International Roam Zone, you will be restricted from accessing Service through any non-participating Canada/international carriers that may otherwise be included in our generally available Canada and international data roam zones. Requires minimum one-year agreement and you must remain on an eligible Global plan (DataConnect, Smartphone or PDA, as applicable), for a minimum one-year term. <strong>DataConnect Global:</strong> Includes up to 100MB of data usage in Select International Roam Zone per month. Voice access is restricted and prohibited. <strong>Global Plans for Smartphones and PDAs:</strong> Eligible voice plan is required. Include up to 20MB of data usage in Select International Roam Zone per month. If combined with a voice plan that includes international voice roaming, your international voice roaming in countries included in the Global data plan's Select International Roam Zone will be limited to the participating Canada/international carriers and you will be restricted from voice roaming through any non-participating Canada/international carriers that may otherwise be included in our generally available Canada and international voice roam zones.</p>

<p><strong>Additional Terms And Conditions&mdash;Dataconnect North America:</strong> Available countries, coverage and participating international carriers included in the &quot;Select Canada/Mexico Roam Zone&quot; vary from our generally available Canada/international data roam zones and may not be as extensive. Voice access is restricted and prohibited. Includes up to 100MB of data usage in the Select Canada/Mexico Roam Zone per month. Select Canada/Mexico Roam Zone is restricted to select carrier(s) and coverage areas within Canada and Mexico. See <a href="http://att.com/dataconnectglobal " title="" class="body">att.com/dataconnectglobal</a> for a current list of participating carriers and eligible roam zones. Additional data usage in the Select Canada/Mexico Roam Zone is charged at: $0.005/KB. Standard international roaming rates apply to international data usage outside of Canada and Mexico. Under this plan, you will be restricted from accessing Service through any non-participating Canada/Mexico carriers that may otherwise be included in our generally available Canada and international data roam zones. Requires minimum one-year agreement and you must remain on eligible DataConnect North America plan for a minimum one-year term.</p>

<p><strong>Smartphone Connect:</strong> Not available on PDAs/Pocket PCs, RIM&reg; devices and LaptopConnect cards. May only be used with eligible Cingular-certified Smartphones (Motorola MPX 220, Cingular 2125, Audiovox SMT 5600 or such other Smartphones as Cingular may certify for use with these plans). Eligible voice plan required.</p>

<p><strong>PDA Connect:</strong> May only be used with eligible Cingular-certified PDAs/Pocket PCs. Not available on RIM&reg; devices and LaptopConnect cards.</p>

<p><strong>PDA Connect For Good And Smartphone Connect For Good:</strong> Requires compatible Good Server and, with respect to each end user, a compatible Good Client Access License (CAL) for use with an eligible Cingular Good plan. Solution includes software, products and related services provided by Good Technology, Inc. (&quot;Good&quot;), which are subject to applicable Good terms and conditions. Good is solely responsible for all statements regarding, and technical support for, its software, products and services. In the event you cease to be an employee of your company, or if your company ceases to support your Good Client Access License, you may migrate to another Cingular data plan for which you qualify. <strong>PDA Connect for Good:</strong> May only be used with eligible Cingular-certified PDAs/Pocket PCs. Not available on RIM&reg; devices and LaptopConnect cards. <strong>Smartphone Connect for Good:</strong> May only be used with eligible Cingular-certified Smartphones (Motorola MPX 220, Cingular 2125, Audiovox SMT 5600 or such other Smartphones as Cingular may certify for use with these plans). Not available on PDAs/Pocket PCs, RIM&reg; devices and LaptopConnect cards.</p>

<p><strong>Xpress Mail<sup>TM</sup> Service:</strong> Eligible data plan required. Not available with DataConnect plan activation on LaptopConnect card. You may cancel Xpress Mail at any time. You will be billed for all usage up to cancellation of Xpress Mail. Measured usage will be charged as specified in your plan. Xpress Mail leverages point-to-point secure encryption, using the following technologies: AES and SSL. Cingular provides devices that support both AES and SSL. Cingular encrypts and stores your email address and password to enable delivery of your email to your device.</p>

<p><strong>Pda Connect For BlackBerry&reg; Connect:</strong> Exclusively for select non-BlackBerry devices. May be used with BlackBerry&reg; Enterprise Server<sup>TM</sup> for corporate access (behind the firewall) to Microsoft&reg; Exchange and Lotus Domino email and personal information management; valid Client Access License(s) required. Includes BlackBerry&reg; Internet Service<sup>TM</sup> (BIS) for individual access to up to 10 Internet email accounts including AOL, Yahoo! and POP3/IMAP4 Internet Service Providers. If more than 1,000 emails reside on the BIS server or email is older than 30 days, it may be automatically deleted. Mail Connector is not supported.</p>

<p><strong>BlackBerry&reg; Enterprise, BlackBerry&reg; Enterprise Max, BlackBerry&reg; Tethered And Blackberry International:</strong> Exclusively for use with BlackBerry&reg; devices. May be used with BlackBerry&reg; Enterprise Server<sup>TM</sup> for corporate access (behind the firewall) to Microsoft Exchange, Lotus Domino and Novell&reg; GroupWise email and personal information management; valid Client Access License(s) required. Includes BlackBerry&reg; Internet Service (BIS) for individual access to up to 10 Internet email accounts including AOL, Yahoo! and POP3/IMAP4 Internet Service Providers. If more than 1,000 emails reside on the BIS server or email is older than 30 days, it may be automatically deleted. Individual access to Microsoft Exchange and Lotus Domino requires Mail Connector software, which can be downloaded from <a href="http://att.com/blackberrystart" title="" class="body">att.com/blackberrystart</a> (BIS setup site). BlackBerry&reg; Tethered: Requires Cingular Communication Manager 5.2 or higher and BlackBerry&reg; Handheld software 4.1 or higher. BlackBerry&reg; International: Requires minimum one-year agreement and you must remain on eligible BlackBerry&reg; International plan for a minimum one-year term.</p>

<p><strong>BlackBerry&reg; Personal And BlackBerry&reg; Personal Max:</strong> Exclusively for use with BlackBerry&reg; devices. Includes BlackBerry&reg; Internet Service (BIS) for individual access to up to 10 Internet email accounts including AOL, Yahoo! and POP3/IMAP4 Internet Service Providers. If more than 1,000 emails reside on the BIS server or email is older than 30 days, it may be automatically deleted. May not be used to access corporate email; use with Mail Connector and/or BlackBerry&reg; Enterprise Server prohibited.</p>

<p><strong>Smartphone Connect For Microsoft Direct Push And Pda Connect For Microsoft Direct Push:</strong> Requires Microsoft Exchange 2003 Server with Service Pack 2 and, with respect to each end user, a compatible device operating on a Windows Mobile 5 platform (with Message Security Feature Pack) and an email account enabled with Direct Push. Plans include end user and IT help desk customer support from Cingular for Windows Mobile 5 and device side ActiveSync issues. Cingular does not sell, supply, install or otherwise support Microsoft software, products or services (including without limitation, Exchange and Direct Push). In the event you cease to be an employee of your company, or if your company ceases to support a compatible Exchange Server, you may migrate to another Cingular data plan for which you qualify.</p>

<p><strong>PDA Connect for Microsoft Direct Push:</strong> May only be used with eligible Cingular-certified PDAs/Pocket PCs. Not available on RIM&reg; devices and LaptopConnect cards.</p>

<p><strong>Smartphone Connect for Microsoft Direct Push:</strong> May only be used with eligible Cingular-certified Smartphones. Eligible voice plan required. Not available on PDAs/Pocket PCs, RIM&reg; devices and LaptopConnect cards.</p>

<p><strong>Pooled Data Connect Plans:</strong> Available only to customers with a qualified Cingular Wireless business or government agreement (&quot;Business Agreement&quot;) and their respective Corporate Responsibility Users (&quot;CRUs&quot;). Consolidated billing is required. WIN Advantage&reg; may also be required. Customer's CRUs may activate service on the Pooled Data Connect Plans described in this brochure (&quot;Pooled Plans&quot;). Within a single Foundation Account (FAN), Customer's CRUs on an eligible Pooled Plan aggregate or &quot;pool&quot; their included data usage (&quot;Included Usage&quot;), creating a &quot;Pool&quot;. To pool together, each CRU in the Pool must subscribe to a Pooled Data Connect Plan that has the same amount of Included Usage and the same Additional Kilobyte charge (&quot;Similar Pooled Plan&quot;). Every billing cycle, each CRU first uses his or her Included Usage. If a CRU does not use all his or her Included Usage it creates an underage in the amount of unused kilobytes (&quot;Under Usage&quot;). If a CRU uses more than his or her Included Usage it creates an overage with respect to kilobytes of data usage (&quot;Over Usage&quot;). The Pool's Under Usage kilobytes and Over Usage kilobytes are then aggregated respectively and compared. If the aggregate Under Usage kilobytes exceed the aggregate Over Usage kilobytes, then no CRU in the Pool pays Additional Kilobyte charges. If the aggregate Over Usage kilobytes exceeds the aggregate Under Usage kilobytes, then the ratio of Under Usage kilobytes to Over Usage kilobytes is applied to the data usage of each CRU in the Pool with Overage Usage, resulting in a monetary credit against the corresponding Additional Kilobyte charges. For example, if a Pool has 900 Under Usage kilobytes and 1000 Over Usage kilobytes (90%), then each CRU with Over Usage will receive a credit equal to 90% of his or her Additional Kilobyte charges. CRUs changing price points or migrating to Pooled Plans during a bill cycle may result in one-time prorations or other minor impacts to the credit calculation. Credits will only appear on WIN Advantage&reg;. Customer may have more than one Pool within a FAN provided that Customer may only have one Pool for Similar Pooled Plans within a FAN; however, an individual CRU can only be in one Pool at a time. Cingular reserves the right to limit the number of CRUs in a Pool due to business needs and system limitations. CRUs on Pooled Plans and CRUs participating in a legacy Pooled Data Connect plan pool created prior to February 17, 2006 (&quot;Legacy Pool&quot;) cannot be in the same Pool but can be within the same FAN. End users on non-pooling Cingular plans may be included in the same FAN as CRUs on pooled plans; however these non-pooling end users will not receive the pooling benefits or contribute Included Usage to a pool.</p>

<br>

<strong class="big">3) TERMS APPLICABLE TO FEATURES:</strong>

<p>Certain features will not be available in all areas at all times. See Roadside Assistance welcome letter and/or brochures for full terms and conditions.</p>

<p><strong>Wireless Phone Insurance:</strong> Underwritten by Continental Casualty Company, a CNA company (CNA) and administered by Asurion, LLC (Asurion Insurance Agency, LLC CA Lic#OD63161), a licensed agent of CNA. May not be available in all states. A $50 non-refundable deductible per approved insurance replacement applies. See a Wireless Phone Insurance brochure for complete terms and conditions on coverage, available at participating Cingular locations or att.com/wireless. Customers have 30 days from activation or upgrade to enroll. Eligibility varies by device.</p>

<p><strong>VoiceDial:</strong> Regular airtime charges apply. Mobile to Mobile Minutes do not apply. Calls to 911, 411, 611, 711 and international dialing cannot be completed with VoiceDial Services. Caller ID cannot be blocked. Caller ID will be delivered on calls, even if you have permanently blocked your name and number.</p>

<p><strong>Connecticut Customers:</strong> Questions About Your Service: If you have any questions or
concerns about your service, please call Customer Care at 1-800-331-0500 or dial 611 from your
wireless phone. If you are a Connecticut customer and we cannot resolve your issue, you have
the option of contacting the Department of Public Utility Control (DPUC). Online:
www.state.ct.us/dpuc; Phone: 866-381-2355; Mail: Connecticut DPUC, 10 Franklin Square, New
Britain, CT 06051.</p>

<p>HBO Mobile<sup>SM</sup> and HBO Mobile Family<sup>SM</sup> are service marks of Home Box Office, Inc. HBO Content &copy;2006 Home Box Office, Inc.</p>

<p>&copy;2006 Cingular Wireless, LLC. All rights reserved.</p>
