<!-- BEGIN Include terms.php -->

<table width="925" border="0" cellspacing="0" cellpadding="0" align="center">
<tr>
	<!-- Label Tab -->
	<td height="24" colspan="3" background="images/TabTop.gif" class="bodyWhite"><strong>&nbsp;&nbsp;Terms &amp; Conditions</strong></td>
</tr>
<tr>
	<!-- Left border -->
	<td width="2" bgcolor="#E20074">
		<img src="images/spacer.gif" alt="" width="2" height="2" border="0">
	</td>
	<!-- Content -->
	<td align="center" bgcolor="#FFFFFF">
		<img src="images/spacer.gif" alt="" width="1" height="12" border="0"><br>
		<table width="900" border="0" cellspacing="0" cellpadding="0" align="center">
		<tr>
			<td class="bodyBlack">
				<!-- Text -->
				<?
				// MI Terms
				if ((!$terms) || $terms == "mi"){
					echo'
				<table width="100%">
				<tr>
					<td class="bigBlack"><strong><u>Mobile Intentions Terms & Conditions:</u></strong></td>
					<td align="right" class="bodyBlack">
						<a href="?sec=terms&terms=tmobile&zipcode='.$zipcode.'" class="bodyBlack">T-Mobile Terms & Conditions</a> | <a href="?sec=terms&terms=rebates&zipcode='.$zipcode.'" class="bodyBlack">Rebate Terms & Conditions</a>
					</td>
				</tr>
				<tr>
					<td colspan="2" class="smallBlack"><br>
		 				<ol>
  							<p><li>Mobile Intentions ("MI") fulfills orders for the promotion that contains these Terms & Conditions (the "Promotion"). MI is an independent contractor for the business offering the Promotion (the "Promoter"). MI and the Promoter are not the same company or business. The website that offers the Promotion (the "Website") is part of the service offered by MI to the Promoter, and does not mean that MI and the Promoter are partners or affiliates of each other.</li></p>

						<p><li>These Terms & Conditions control over anything that the employees of the Promoter say about the Promotion. MI is not in control of the information that is communicated to you by the Promoter, and therefore can offer the Promotion strictly on these Terms & Conditions. If you have been told anything by the Promoter that is different from these Terms & Conditions, please tell us of those differences. However, under no circumstances is MI required to honor terms that are not in these Terms & Conditions.</li></p>

						<p><li>MI is an independent dealer of wireless services for the wireless service carriers offered in this Promotion. MI is not a partner, subsidiary or affiliate of any of those carriers. MI does not provide the wireless services and MI is not a manufacturer of any phones or other equipment that you get through the Promotion. Wireless billing issues, service issues, or phone/equipment problems are handled by the wireless carrier or the product manufacturer. MI does not have the right or ability to address billing issues for you with the wireless carrier.</li></p>

						<p><li>If you get wireless services or phones/equipment, you are also bound by the terms and conditions of the wireless carrier giving you wireless services and products including, but not limited to, return policy and cancellation policies. Please read the carrier terms and conditions before you subscribe for services through this Promotion. Your cancellation of services or return of phones/equipment may be subject to penalties and fees charged by the carriers in addition to any penalties and fees charged by MI.</li></p>

						<p><li>The information on the Website about the prices and costs of services and/or phones/equipment control over anything that the employees of the Promoter say about the Promotion. If your were told by an employee of representative of the Promoter prices or details of the Promotion that are different than what you see on the Website, you must disregard what you were told by the employee of representative of the Promoter.</li></p>

						<p><li>The information that you enter for your order will be subject to processing by MI. It is possible that the services or phones/equipment that you requested in your order will need to be changed. So, you should not consider the order information that you submitted final until you receive confirmation from MI.</li></p>

						<p><li>Every wireless carrier has credit restrictions. The information that you provided in your order will be used to review your credit history and score. This credit review process is not handled by MI. It is strictly handled by the wireless carriers, and is done according to the carrier\'s terms and conditions. MI only communicates the necessary information to the wireless carrier. MI does not receive a copy of your credit report or any information about your credit, except whether your credit is acceptable to the wireless carrier. MI will tell you whether your credit is acceptable by the wireless carrier, but MI will not have information about why your credit was or was not acceptable to the wireless carrier. MI has its own Privacy Policy, which you can read by clicking on the MI Privacy Policy link on the Promotion\'s website.</li></p>

						<p><li>All offers in this Promotion are valid only with a new activation with approved credit, and are not valid for additional lines, renewals or upgrades. Adding new data service to existing voice service is an upgrade, which does not qualify for any offer. Furthermore, all activations that qualify for the offers in this Promotion require a one-year service agreement through T-Mobile.</li></p>

						<p><li>You are responsible for verifying whether you will have wireless service coverage and quality where you need it. MI cannot know how or where you will be using the wireless services, and thus cannot advise you about whether you will have the level of service you will need where you need it.</li></p>

						<p><li>The credit card information that you provide to MI must be valid and have available credit limit exceeding $350 (the "Credit Card") in order to qualify for the offering of the Promotion. In addition to providing payment for amounts required by this Promotion, the Credit Card will be used to secure the payment of any penalties and fees from cancellation of services. If you cancel your services in a way that subjects you to penalties and fees, you authorize MI to charge the Credit Card, without additional authorization, the amounts of penalties and fees owed by you to MI.</li></p>

						<p><li>If any part of your service is canceled or reduced within the following time periods (the "No Cancellation Period"), you will be subject to certain penalties and fees:</p>

						<ul>
							<li type="disc">T-Mobile - 120 days from the date of activation of wireless services</li>
						</ul>

						<p><li>If any part of your service is canceled or reduced within the No Cancellation Period, you will be charged the following penalties and fees (the "Cancellation Penalties"):</p>

						<ul>
							<li type="disc">Carrier penalties and fees according to the carrier terms and conditions<br>
							<li type="disc">$350 penalty paid to MI for each data-enabled phone/equipment (T-Moble only)<br>
							<li type="disc">$150 penalty paid to MI for each non-data enabled phone/equipment (T-Mobile only)</li>
						</ul>

						<p><li>The Cancellation Penalties may be refunded to you (the "Cancellation Refund") if you (i) cancel your service within the carrier\'s "trial period," and (ii) return the phone/equipment that is subject to the Cancellation Penalties in strict compliance with MI return procedures. The carrier\'s "trial period" is set forth in the carrier\'s terms and conditions as the time period that you have to try your services and cancel without penalties or fees.</li></p>

						<p><li>To be eligible for a Cancellation Refund (i) you must return all phones/equipment that are subject to the Cancellation Penalties in as-new condition with all accessories and documentation in the original manufacturer\'s packaging; and (ii) MI must actually receive what is described in (i) no later than 30 days after the date the cancelled service was activated. MI will have the right to inspect all items returned before authorizing the issuance of the Cancellation Refund. The Cancellation Refund, if authorized, will be sent to you 30 to 60 days after MI receives the return. All returns must be sent postage prepaid to:</p>

						<ul>
							Mobile Intentions<br>
							c/o Wireless Business Solutions - Fulfillment Department<br>
							321 N. Central Expressway<br>
							Suite 250<br>
							McKinney, TX 75070</li>
						</ul>

						<p><li>MI will attempt to collect from you any amounts that you owe MI that are not recovered through the Credit Card. These collection efforts may include reporting to credit agencies and legal action. You will be liable to MI for the reasonable and necessary costs and legal fees incurred by MI to collect the amounts that you owe MI. Any legal action to collect these amounts subject to Texas law, and may be filed in Collin County, Texas, regardless of your residence location.</li></p>

						<p><li>The phones/equipment and rebates offered in this Promotion are subject to availability. If a phone/equipment is not available for purchase, MI will attempt to have a comparable phone/equipment available.</li></p>

						<p><li>The time required to deliver your phones/equipment to you very according to the availability of the phones and other delivery conditions. MI typically delivers within 5 business days. Offers in this Promotion are available only to persons that are 18 years old or over.</li></p>

						<p><li>If you are eligible for a mail-in rebate, please read the MI Rebate Terms & Conditions before you enter your order.</li></p>
						</ol>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="right" class="bodyBlack">
						<a href="?sec=terms&terms=tmobile&zipcode='.$zipcode.'" class="bodyBlack">T-Mobile Terms & Conditions</a> | <a href="?sec=terms&terms=rebates&zipcode='.$zipcode.'" class="bodyBlack">Rebate Terms & Conditions</a>
					</td>
				</tr>
				</table>
					';
				// T-Mobile Terms
				}elseif ($terms == "tmobile"){
					echo'
				<table width="100%">
				<tr>
					<td class="bigBlack"><strong><u>T-Mobile Terms & Conditions:</u></strong></td>
					<td align="right" class="bodyBlack">
						<a href="?sec=terms&terms=rebates&zipcode='.$zipcode.'" class="bodyBlack">Rebate Terms & Conditions</a> | <a href="?sec=terms&terms=mi&zipcode='.$zipcode.'" class="bodyBlack">Mobile Intentions Terms & Conditions</a>
					</td>
				</tr>
				<tr>
					<td colspan="2" class="smallBlack"><br>
<!--						<p class="bodyBlack"><strong>Legal Terms</strong></p>

						<p><strong>SITE USE AND CONTENT</strong><br>
						You may view, copy or print pages from this site solely for personal, non-commercial purposes. You may not otherwise use, modify, copy, print, display, reproduce, distribute or publish any information from this site without the express permission of T-Mobile. At any time T-Mobile may without notice make changes to this site or to the services or products described in this site.</p>

						<p><strong>WARRANTIES AND LIMITATIONS OF LIABILITY<br>
						INFORMATION IN THIS WEB SITE IS PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. T-Mobile SHALL NOT BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL OR OTHER DAMAGES FOR USE OF THIS WEB SITE OR OTHER HYPERLINKED WEB SITES.
SECURITY</strong></p>

						<p>T-Mobile uses reasonable precautions to protect the privacy of your credit card and other ordering information by utilizing a Secure Socket Layer ("SSL") connection. Accordingly, your credit card and other ordering information, such as your name and address, is encrypted using the SSL connection and is not expected to be read in an intelligible form as it travels to T-Mobile order processing system. T-Mobile order processing systems is not connected to the Internet and is not accessible to the public.</p>

						<p>Many web browsers support the use of an SSL connection, but if your browser does not support the use of an SSL connection or if you prefer not to send your credit card number over the Internet, you can place your order by calling T-Mobile toll free at 1-800-T-Mobile (U.S. only).</p>

						<p>Please protect your username and password. If you access your account from a public computer be sure to log off before closing the browser window.</p>

						<p><strong>PURCHASING PRODUCTS & SERVICES ON LINE</strong></p>
						<ol>
							<p><li><strong><u>General</u></strong> User agrees to purchase the products and services ordered on the various order screens when user clicks on the "SUBMIT" or similar button on the product or service order screens. The terms of the purchase agreement include the information included on the various order screens and the terms of this section. Such agreement is in addition to and not in lieu of the agreement with user formed by user\'s use of the Internet site.</li></p>

							<p><li><strong><u>No Warranties by T-Mobile</u></strong> T-Mobile MAKES NO EXPRESS REPRESENTATIONS OR WARRANTIES ABOUT ITS SERVICES AND DISCLAIMS ANY IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. T-Mobile DOES NOT AUTHORIZE ANYONE TO MAKE A WARRANTY OF ANY KIND ON ITS BEHALF AND USER MAY NOT RELY ON ANY STATEMENT OF WARRANTY. T-Mobile IS NOT THE MANUFACTURER OF THE PRODUCTS AND THE ONLY WARRANTY APPLICABLE TO THE PRODUCTS USED IN CONNECTION WITH THE SERVICES IS THAT PROVIDED BY THE PRODUCT MANUFACTURERS. THIS SECTION SURVIVES TERMINATION OF THIS AGREEMENT.</li></p>

							<p><li><strong><u>Product Warranty by Manufacturer</u></strong> 
Each T-Mobile product comes with a limited warranty provided by the manufacturer. The warranty for the products that you ordered is either included with the product itself or can be obtained from the product manufacturer.</li></p>

							<p><li><strong><u>Limitation of Liability</u></strong> Neither T-Mobile nor any of its affiliates, nor the directors, employees or other representatives of any of them, is liable for damages arising out of or in connection with the use of the products. This is a comprehensive limitation of liability that applies to all damages of any kind, including compensatory, direct, indirect or consequential damages, loss of data, income or profit, loss of or damage to property and claims of third parties.</li></p>

							<p><li><strong><u>Shipping and Billing to US Address Only; Product Availability</u></strong> T-Mobile does not process orders to foreign shipping or billing addresses. T-Mobile tries to give product availability information on this Internet site, but sometimes products are unexpectedly unavailable. In addition, T-Mobile updates and improves its products and services on a continuous basis. T-Mobile will inform you if any T-Mobile products that you ordered turn out to be unavailable or if any service that you ordered has been changed. T-Mobile may use e-mail to inform you.</li></p>

							<p><li><strong><u>Prices, Taxes and Shipping & Handling</u></strong> All prices are stated and payable in US dollars. The prices for products and services quoted on this Internet site do not include taxes.
T-Mobile charges all applicable taxes on products and services.</p>

							<p>Shipping charges shall be at current rates and will be included in the charges to your credit card purchase.</li></p>

							<p><li><strong><u>Return Policy</u></strong> T-Mobile products may be returned within 14 days of purchase for refund of the purchase price (but not charges for wireless service). Note the return policy, including the number of days for return, may be changed without notice and the policy may not apply to certain products.</p>

							<p>If you are not satisfied with your purchase of your T-Mobile product, you may return it to T-Mobile by calling 1-800-937-8997 for return information. In order to obtain a full refund of the original purchase price of the T-Mobile product, you must return the product at your expense in an undamaged condition and complete with all the accessories that came with the product in the original box with all materials and package inserts within 14 days of your purchasing the handset. A copy of your receipt (which was enclosed when T-Mobile shipped the products to you) must accompany the return.</p>

							<p>Upon T-Mobile receipt of the returned product, T-Mobile will credit your credit card account number used for the original purchase, and, in case if a returned T-Mobile phone, net of any outstanding balance on the account associated with the returned phone.</p>

							<p>T-Mobile cannot exchange products through the Internet site, rather the user should return the product for a refund within the appropriate time period and purchase a new product over the Internet site.</li></p>
						</ol>
						<p><strong>CUSTOMER COMMENTS</strong><br>
						T-Mobile welcomes the submission of comments, information or feedback through this site; however, T-Mobile does not want to receive confidential or proprietary information from you. By submitting information through this site you agree that the information shall not be considered confidential and shall become the property of T-Mobile, including an assignment of all rights and titles to such information. T-Mobile shall have the unrestricted right to use such information for any purpose and without compensation to the submitting party.</p>

						<p><strong>HANDSET RETURN AND CANCELLATION POLICY</strong><br>
						There is a Return Period during which you can cancel Service without paying a cancellation fee. The Return Period is 14 calendar days from the date of Service Activation (30 days in CA) or 30 days from the Product\'s purchase date if you have not activated Service. During the Return Period, you can cancel Service for any reason so long as you: (a) contact us to cancel Service; and (b) return to the place of purchase, with proof of purchase, any Product purchased from us or our authorized dealer in connection with your purchase of Service. Even if you cancel Service and/or return your Product, you must pay all Service and other charges incurred prior to cancellation or return. A Product returned with proof of purchase to the place of purchase during the Return Period along with its original packaging and contents is eligible for a refund of the purchase price if it is in good working condition. You may be required to pay a restocking fee. The purchase price of your Product may have been subsidized to facilitate your subscription to the Service. If you cancel Service within the Return Period but do not return the Product in good working condition, you will be charged for the amount of the subsidy you received.</p>

						<p><strong>T-MOBILE PRIVACY NOTICE</strong><br>
						T-Mobile USA, Inc. and its affiliates (collectively "T-Mobile") has prepared this privacy notice ("Notice") to describe what information about you is collected and how that information may be used, disclosed and protected when you access or use any of our services via the Internet or through any wireless device that allows Internet access. This Notice does not apply to information that may be collected offline. T-Mobile may revise or update this Notice from time to time, so you should refer back to this page often for the latest information.</p>

						<br>
						<p><strong class="bodyBlack">T-MOBILE TERMS AND CONDITIONS</strong><br>-->
						<em>Effective 12/04 until amended</em></p>

						<p>Welcome to T-Mobile. <strong>BY ACTIVATING OR USING OUR SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS ("T&C\'s"). PLEASE READ THESE T&C\'s CAREFULLY. They affect your legal rights by, among other things, requiring MANDATORY ARBITRATION OF DISPUTES and charging an EARLY CANCELLATION FEE. IF YOU DO NOT AGREE TO THESE T&C\'s, DO NOT ACTIVATE OR USE THE SERVICE OR YOUR WIRELESS PHONE, DEVICE, SMART CARD, OR OTHER EQUIPMENT ("PHONE") AND FOLLOW THE DIRECTIONS IN SEC. 5 BELOW.</strong></p>

						<p>These T & C\'s and your Service Agreement (if any) constitute your agreement with T-Mobile USA, Inc. and its affiliates (together, "T-Mobile," "we," or "us") for any wireless services and other telecommunications services that we provide you ("T-Mobile Services"), any applications, Phones, or products that you purchase or obtain from us or use with the Service ("Products"), and any applications or services that you purchase, obtain, or use that are provided through or with the Service, or billed to your T-Mobile account ("Third-Party Services") (T-Mobile Services and Third-Party Service together, the "Service"). These T&C\'s supercede all earlier versions. To the extent these T&C\'s conflict with the T-Mobile Terms and Conditions you receive with your Phone, these T&C\'s apply. Rate plan and feature information for the Services you select or use are available to you when you purchase the Service at retail locations and on our website, and are a part of our agreement and are incorporated by reference into these T&C\'s (the T&C\'s, your Service Agreement and the rate plan information together are referred to as the "Agreement"). You acknowledge that no employee, dealer or other agent is authorized to make any representation or warranty (other than as described in the Agreement or our current materials) with respect to the Agreement, Service, Products or rate plans and offerings, or to waive or modify any terms or provisions of the Agreement.</p>
						<ol>

							<p><li><strong><u>Acceptance of Agreement.</u></strong> You accept this Agreement by: (i) activating or using the Service; (ii) signing, orally or electronically accepting the Agreement; or (iii) are deemed to accept the Agreement, whichever occurs first. You must activate Service within 30 days after purchase of your Phone (unless returned as provided in Sec. 5). If you don\'t activate Service within 30 days, you are deemed to accept the Agreement, and you agree to pay monthly Service charges for the Term according to your rate plan.</li></p>

							<p><li><strong><u>MANDATORY ARBITRATION TO RESOLVE DISPUTES/ CLASS ACTION WAIVER/JURY TRIAL WAIVER: ARBITRATION.</u></strong> PLEASE READ THIS PROVISION CAREFULLY. IT MEANS THAT, EXCEPT AS NOTED BELOW, YOU AND WE WILL ARBITRATE OUR DISPUTES. ANY CLAIM OR DISPUTE BETWEEN YOU AND US IN ANY WAY RELATED TO OR CONCERNING THE AGREEMENT, OR THE PROVISION OF SERVICES OR PRODUCTS TO YOU, INCLUDING ANY BILLING DISPUTES ("CLAIM"), SHALL BE SUBMITTED TO FINAL, BINDING ARBITRATION BEFORE THE AMERICAN ARBITRATION ASSOCIATION ("AAA").</strong> This agreement to arbitrate also requires you to arbitrate claims against other parties relating to Services or Products provided or billed to you, including suppliers of Services and Products and our retail dealers, if you also assert Claims against us in the same proceeding. You and we acknowledge that the Agreement affects interstate commerce and that the Federal Arbitration Act and federal arbitration law apply to arbitrations under the Agreement (despite the choice of law provision in Sec. 23).</p>

							<p>BEFORE INSTITUTING ARBITRATION, YOU AGREE TO PROVIDE US WITH AN OPPORTUNITY TO RESOLVE YOUR CLAIM BY SENDING A WRITTEN DESCRIPTION OF YOUR CLAIM TO US AT T-MOBILE CUSTOMER RELATIONS, P.O. BOX 37380, ALBUQUERQUE, NM 87176-7380 AND NEGOTIATING WITH US IN GOOD FAITH REGARDING YOUR CLAIM. IF WE ARE NOT ABLE TO RESOLVE YOUR CLAIM WITHIN 30 DAYS OF RECEIPT OF YOUR NOTICE, THEN YOU OR WE, INSTEAD OF SUING IN COURT, MAY INITIATE ARBITRATION PROCEEDINGS WITH THE AAA. YOU MUST SERVE OUR REGISTERED AGENT (SEE SEC. 20) IN ORDER TO BEGIN AN ARBITRATION. ARBITRATION WILL BE CONDUCTED UNDER THE AAA\'S PUBLISHED WIRELESS INDUSTRY ARBITRATION RULES AND SUPPLEMENTAL PROCEDURES FOR CONSUMER-RELATED DISPUTES, WHICH ARE AVAILABLE BY CALLING THE AAA AT 800-778-7879 OR VISITING ITS WEB SITE AT www.adr.org. The AAA has a fee schedule for arbitrations. You will pay your share of the arbitrator\'s fees and administrative expenses ("Fees and Expenses") except that: (a) for Claims less than $25, we will pay all Fees and Expenses; and (b) for Claims between $25 and $1,000, you will pay only $25 in Fees and Expenses, or any lesser amount as provided under AAA\'s Supplemental Procedures for Consumer-Related Disputes. <strong>You and we agree to pay our own other fees, costs, and expenses, including those for any attorneys, experts, and witnesses.</strong> An arbitrator may only award as much and the type of relief as a court with jurisdiction in the place of arbitration that is consistent with law and this Agreement. An arbitrator may issue injunctive or declaratory relief but only applying to you and us and not to any other customer or third party. <strong>As a limited exception to the agreement to arbitrate, you and we agree that:</strong> (a) you may take Claims to small claims court, if your Claims qualify for hearing by such court; and (b) if you fail to timely pay amounts due, we may assign your account for collection, and the collection agency may pursue in court claims limited strictly to the collection of the past due debt and any interest or cost of collection permitted by law or the Agreement.</p>

							<p><strong><u>CLASS ACTION WAIVER.</u> WHETHER IN COURT, SMALL CLAIMS COURT, OR ARBITRATION YOU AND WE MAY ONLY BRING CLAIMS AGAINST EACH OTHER IN AN INDIVIDUAL CAPACITY AND NOT AS A CLASS REPRESENTATIVE OR A CLASS MEMBER IN A CLASS OR REPRESENTATIVE ACTION. NOTWITHSTANDING SEC. 22, IF A COURT OR ARBITRATOR DETERMINES IN A CLAIM BETWEEN YOU AND US THAT YOUR WAIVER OF ANY ABILITY TO PARTICIPATE IN CLASS OR REPRESENTATIVE ACTIONS IS UNENFORCEABLE UNDER APPLICABLE LAW, THE ARBITRATION AGREEMENT WILL NOT APPLY, AND YOU AND WE AGREE THAT SUCH CLAIMS WILL BE RESOLVED BY A COURT OF APPROPRIATE JURISDICTION, OTHER THAN A SMALL CLAIMS COURT.</strong></p>

							<p><strong><u>JURY TRIAL WAIVER.</u> WHETHER ANY CLAIM IS IN ARBITRATION OR IN COURT (AS PROVIDED IN THIS SEC. 2) YOU AND WE WAIVE ANY RIGHT TO JURY TRIAL INVOLVING ANY CLAIMS OR DISPUTES BETWEEN YOU AND US.</strong></li></p>

							<p><li><strong><u>Changes to the Agreement or Charges.</u></strong> EXCEPT TO THE EXTENT PROHBIITED BY LAW, IF WE: (A) INCREASE THE CHARGES INCLUDED IN YOUR MONTHLY RECURRING ACCESS RATE PLAN, OR (B) MODIFY A MATERIAL TERM OF OUR AGREEMENT WITH YOU AND THE MODIFICATION WOULD BE MATERIALLY ADVERSE TO YOU, WE WILL NOTIFY YOU OF THE INCREASE OR MODIFICATION AND YOU CAN CANCEL THAT SERVICE WITHOUT PAYING A CANCELLATION FEE (WHICH IS YOUR ONLY REMEDY) BY FOLLOWING THE CANCELLATION INSTRUCTIONS IN THE NOTICE. IF YOU DO NOT CANCEL YOUR SERVICE BY FOLLOWING THOSE INSTRUCTIONS, OR YOU OTHERWISE ACCEPT THE CHANGE, THEN YOU AGREE TO THE INCREASE OR MODIFICATION, EVEN IF YOU PAID FOR SERVICE IN ADVANCE. IF THE NOTICE DOES NOT SAY HOW LONG YOU HAVE TO CANCEL, THEN IT IS WITHIN 14 DAYS AFTER THE DATE OF THE NOTICE, UNLESS A LONGER PERIOD IS REQUIRED BY LAW. EXCEPT TO THE EXTENT PROHIBITED BY LAW, CHARGES FOR PRODUCTS, SERVICES, OPTIONAL SERVICES, OR ANY OTHER CHARGES THAT ARE NOT INCLUDED IN YOUR MONTHLY RECURRING ACCESS RATE PLAN (SUCH AS DIRECTORY ASSISTANCE, ROAMING, DOWNLOADS AND THIRD-PARTY CONTENT) ARE SUBJECT TO CHANGE AT ANY TIME WITHOUT NOTICE, AND IF YOU CONTINUE TO USE THOSE SERVICES, OR YOU OTHERWISE AGREE TO THE CHANGES, THEN YOU AGREE TO THE NEW CHARGES. VISIT OUR WEBSITE, RETAIL LOCATIONS, OR CALL CUSTOMER CARE FOR CURRENT CHARGES.</li></p>

							<p><li><strong><u>Term; Cancellation of Service.</u></strong> If you select a rate plan with a fixed term longer than 1 month, then this Agreement will continue for the full number of months selected ("Term"). <strong>You may cancel Service for any reason by providing us with notice (we may require up to 30 days), which cancellation will take effect on or before the beginning of the next billing cycle after the notice period, BUT IF YOU CANCEL SERVICE OR BREACH THE AGREEMENT BEFORE YOUR TERM ENDS, YOU AGREE THAT THE RESULTING HARM TO US IS IMPRACTICABLE OR EXTREMELY DIFFICULT TO MEASURE AND YOU AGREE TO PAY US IN ADDITION TO AMOUNTS OWED, AS A REASONABLE ESTIMATE OF OUR HARM, A $200 CANCELLATION FEE PER NUMBER (which may be deducted from your deposit or any amounts prepaid by you, charged to your card or billed to your account). Our cost of providing your Service and Phone is not incurred evenly over the Term. Our monthly charges and other rates are based on the assumption that you will remain a customer for the whole Term. You and we agree that it is reasonable for your rates to include the amount of the cancellation fee. We may suspend or terminate your Service for any reason or no reason upon 3 days notice (unless a longer period is required by law). If you breach the Agreement, we may suspend or terminate your Service immediately without prior notice (except to the extent prohibited by law) and do the same for any other service you receive under any other agreement with us. <u>You breach the Agreement by:</u></strong> (a) failing to pay any sum when due; (b) failing to comply with any provision in this Agreement or any other agreement between us; (c) becoming the subject of any proceedings under the Bankruptcy Code; (d) becoming insolvent; or (e) your financial institution dishonoring or returning for insufficient funds your check or credit card. In the event of cancellation, you are responsible for payment of all charges (including any cancellation fee) due to us under the Agreement, which charges will be immediately due and payable. If we reinstate Service to you after discontinuing Service, you may be subject to a credit check and agree to pay reactivation charges or deposits. After the Term expires, you become a month-to-month customer but are still subject to the Agreement, as modified.</li></p>

							<p><li><strong><u>Cancellation and Return Policy.</u></strong> There is a Return Period during which you can cancel a newly activated line of Service without paying a cancellation fee. <strong>The Return Period is 14 calendar days from the date of Service activation or 30 days from the Phone\'s purchase date if you have not activated Service (the Return Period may be longer in some states, such as CA - visit www.t-mobile.com, or ask a sales or customer care representative). Even if you cancel Service, you must pay all Service and other charges incurred prior to cancellation.</strong> In order to receive a refund of the purchase price (minus shipping and rebates) of your Phone, you must return it in "like-new" condition with proof of purchase to the place of purchase during the Return Period along with its original packaging and contents. You may be required to pay a restocking fee. The purchase price of your Phone may have been subsidized to facilitate your subscription to the Service. <strong>If you cancel service and do not return the Phone in "like-new" condition within the Return Period, you will be charged for the difference between the full retail price of the Phone without activation (which may be more than the price with Service activation) and the price you paid for the Phone (minus rebate).</strong> This Sec. 5 does not apply to Phone upgrade, replacement, exchange or other similar programs; see those program materials for details.</li></p>

							<p><li><strong><u>Service Availability and Limits.</u> Your Phone operates as a radio and Service is only available when your Phone is within range of an antenna providing Service. Coverage maps only approximate our wireless coverage area outdoors; actual service area, coverage and quality may vary and change without notice. There may be gaps in Service within the estimated coverage areas shown on coverage maps. Even within a coverage area, factors, such as: network changes, emergencies, traffic volume, transmission limits, service outages, technical limitations, signal strength, your equipment, interconnecting carriers, terrain, structures, weather and other conditions (without limit) may interfere with actual service, quality and availability. Calls may be interrupted, dropped, refused, or limited. Coverage maps may depict coverage in areas where networks are operated by our affiliates and roaming partners; such coverage may change without notice. We are not responsible for those networks and some Services are not available on third-party networks or while roaming. We may impose credit, usage or other limits to Service, cancel or suspend Service, or block certain types of calls, messages or sessions (such as international, 900 or 976 calls) at our discretion. We may suspend Service without notice if you exceed any credit limit. Service may not be transferred to another market except at our discretion, and we may charge transfer fees. WE ARE NOT LIABLE FOR ANY SERVICE LIMITS, FAILURES OR OUTAGES, INCLUDING WITHOUT LIMIT, THE FAILURE OF ALERTS, 9-1-1 EMERGENCY, PRIORITY ACCESS OR SECURE SERVICE CALLS TO BE CONNECTED OR COMPLETED, OR THE FAILURE TO PROVIDE ALERTS OR ACCURATELY LOCATE ANY 9-1-1 CALL (SEE SEC. 14). Location services, including 9-1-1 location services, emergency or other alert systems, priority access and secure service calls may not be available in your area and are subject to the Service limitations in this Sec. 6.</strong></li></p>

							<p><li><strong><u>Use of Service.</u> You may not use, or attempt to use, the Service, the network, or your Phone for any fraudulent, unlawful, improper, harassing, excessive, harmful or abusive purpose ("Improper Uses"), or so as to adversely or negatively impact our customers, employees, business, ability to provide quality service, reputation, or network, or any other person.</strong> We may determine on a case-by-case basis what constitutes Improper Uses. Improper Uses include, without limit: (a) using an automatic dialer or program; (b) sending unsolicited messages or calls; (c) attempting to interfere with the access of any user, host, or network; (d) identity theft; (e) attempting to decipher, decompile, or reverse engineer any software; (f) posting or transmitting unlawful, infringing, or objectionable content as determined by us; (g) probing, or attempting to tamper with or harm our systems, network or customers; or (h) reselling or attempting to resell any aspect of the Service, whether for profit or otherwise. If we suspect a violation of this provision, we may: (i) begin legal action; (ii) suspend or terminate Service immediately and without prior notice; (iii) suspend or terminate service provided to you under any other agreement with us; and (iv) cooperate with law enforcement in prosecuting offenders. You agree to cooperate with us in investigating suspected violations. We may terminate your Service or change your rate plan at any time, with notice, if we determine, in our sole discretion, that your use of the Service is excessive, unusually burdensome, or unprofitable to us. You have no proprietary or ownership rights to a specific wireless telephone number ("Number"), IP address, or e-mail address assigned to you or your Phone; we may change them at any time. You may not program any other Number into your Phone. We may charge you to change your Number.</li></p>

							<p><li><strong><u>Use of Phone with Other Providers/Phone Purchases.</u> Wireless devices and networks do not all use the same technologies. Your Phone may not be compatible with the network and services provided by another wireless service provider and, therefore, may not work with that provider\'s wireless service. You may buy a Phone from us, or from someone else, but it must be GSM/GPRS equipment that is compatible and approved for use with our network and Services and we do not guarantee that all T-Mobile features will be available with such equipment. A T-Mobile Phone may be programmed to accept only a T-Mobile SIM card.</strong></li></p>

							<p><li><strong><u>Changes to Your Account.</u> If you give your personal account validation information to someone, they can access and make changes to your account just as you can.</strong> You may request to switch to another rate plan, and if we authorize the change, a transfer fee may apply and the new rates will become effective by the start of your next billing cycle. <strong>Changes may require your agreement to a new Term (if you select a promotional rate plan or special Phone pricing) or new T&C\'s. If we allow you to temporarily suspend your account, you may continue to pay monthly charges and we may extend the Term for the length of that suspension.</strong></li></p>

							<p><li><strong><u>Deposits.</u></strong> At any time, we may require a deposit from you (in which you grant us a security interest) or increase the amount of your deposit. If we notify you of an increase not associated with a change in rate plan, you may either (a) provide us with the increased deposit or (b) cancel Service within 7 days following the date of the notice (any cancellation fee will be waived). Except to the extent prohibited by law, your deposit may be commingled with other funds and will not earn interest. You may not use your deposit to pay your bills or delay payment, but we can apply your deposit to any charges that you owe us. If Service is cancelled for any reason, any deposit will be applied toward amounts you owe us at or after cancellation. Any remaining deposit will be returned to you at your billing address. Except to the extent prohibited by law, we will not refund any balances of $5 or less unless you contact us to request it. We will hold such money for you for up to 1 year (without accruing interest for your benefit), but you forfeit to us any portion of the money left after 1 year. You also forfeit any money that the U.S. Mail cannot deliver and returns to us.</li></p>

							<p><li><strong><u>Billing, Charges and Late Fees.</u></strong> You authorize us to verify your creditworthiness with a credit-reporting agency at any time. You will be charged for Service and other features on a monthly billing cycle basis and we may change your billing cycle at any time. <strong>You agree to timely pay in full each month all charges and fees associated with the Service, including without limit, monthly recurring Service charges, charges described in Sec. 12, airtime, roaming, long distance, toll, landline access, messages (whether read or unread, solicited or unsolicited), images, sounds, data, features (such as web access, text messages and voicemail), calling services (such as operator or directory assistance and calling card use), additional or optional services that you use or are processed through your Phone (or Number, IP address or email address assigned to or authorized by you), and you remain liable for payment even if a third party agrees to pay your charges. You will be charged for more than one call when you use certain features resulting in multiple inbound or outbound calls (such as call forwarding, call waiting, voicemail retrieval, and conference calling). All lines use and share the airtime and features included in Family or other pooling plans. Mobile to mobile minutes are those used between T-Mobile Phones while on the T-Mobile USA network (and not roaming or affiliate networks). Except to the extent prohibited by law, billing of roaming charges and minutes or Services used may be delayed or applied against included minutes or Services in subsequent billing cycles, which may cause you to exceed your included minutes or Services in a particular billing cycle. Roaming and other call rating (such as time of call) depend on the location of the network equipment providing Service for a particular call and not the location of the Phone. For billing purposes, you agree not to rely on indicators on your Phone (such as roaming and call time), which may be inaccurate. UNUSED MINUTES OR OTHER ALLOTMENTS FROM YOUR RATE PLAN EXPIRE AT THE END OF YOUR BILLING CYCLE AND DO NOT CARRY OVER TO SUBSEQUENT BILLING CYCLES. PARTIAL MINUTES OF AIRTIME USAGE ARE ROUNDED UP AND CHARGED, OR DEDUCTED FROM ANY INCLUDED MINUTES, AS FULL MINUTES; AIRTIME USAGE IS MEASURED FROM THE TIME THE NETWORK BEGINS TO PROCESS THE CALL (BEFORE THE PHONE RINGS OR THE CALL IS ANSWERED) THROUGH ITS TERMINATION OF THE CALL (AFTER YOU HANG UP). FOR BILLING PURPOSES, THE TIME OR DAY (SUCH AS NIGHTS AND WEEKENDS) OF AN ENTIRE CALL IS DETERMINED BY THE TIME THE CALL STARTS. UNLESS OTHERWISE SPECIFIED IN YOUR RATE PLAN MATERIALS, WEEKENDS ARE MIDNIGHT FRIDAY TO MIDNIGHT SUNDAY. NIGHTS ARE 9:00 PM TO 6:59 AM.</strong></p>

							<p><strong><u>Incorrect Charges.</u> If you believe your bill contains an incorrect charge, you have 60 days from the date of the first bill that contains the charge to notify us or you waive any right to dispute the charge.</strong> To notify us, please contact Customer Care at www.t-mobile.com, (800) 937-8997, or 611 from your Phone. We may require you to describe the dispute in writing. Any written communications concerning charges must be sent to the T-Mobile Customer Relations address in Sec. 2. If you accept a credit to resolve an issue, you agree the issue is fully resolved. If Customer Care does not resolve your dispute and you still wish to pursue the matter, follow the dispute resolution process described in Sec. 2. <strong><u>California customers:</u> our Utility number is U-3056-C; if you file a billing related claim with the Consumer Affairs Branch ("CAB") of the CPUC you must, within 24 hours of filing, inform us by writing to the Customer Relations address in Sec. 2 with sufficient information to identify you and your account. If we resolve your dispute, your CAB claim will be deemed resolved at that time, and you agree to promptly withdraw your claim with the CAB. <u>Payments.</u> We may require payment before your due date if we are concerned about your ability to pay us (such as when you have an unusually high balance). For your payment to be deemed received by us and your account to be timely credited, you must provide with your payment information sufficient to identify you and your account (your account number).</strong> If we accept late or partial payments or payments with limiting notations, it will not waive any of our rights to collect all amounts that you owe us and it will not be an accord and satisfaction. If we agree to an alternate payment plan, we may confirm it in any manner, including by electronic means. <strong>If your financial institution dishonors or returns for insufficient funds your check or credit card, it is a breach of this Agreement and we may a) charge you a fee of $20 or such amount as may be permitted by law, b) stop accepting checks, credit card or other similar payment methods from you and c) immediately suspend or cancel your Service. We may use a collection agency and charge you for their fees billed to us for trying to collect what you owe us. <u>Late Fees. You agree to pay 1.5% or $5 per month (or portion of a month), whichever is greater, on any past due balances until paid, subject to the highest amount permitted by law. Except to the extent prohibited by law, this late fee may be charged regardless of any disputes you may have raised regarding your invoiced charges.</u></strong></li></p>

							<p><li><strong><u>Taxes & Fees/Regulatory and Administrative Fees.</u> We bill you for taxes, fees, and other charges (such as sales, use, excise, public utility and other taxes) levied by or remitted to domestic or foreign governments or authorities and imposed on you or us as a result of providing the Service or your Phone ("Taxes & Fees"). Any tax exemption only applies after the date we receive from you acceptable documentation. We will determine, in our discretion, the type and amount of the Taxes & Fees to be billed. These Taxes & Fees may change at any time without notice. We may also bill you for regulatory and administrative fees ($.86 per line per month as of 12/04) to recover our costs of complying with certain regulatory mandates (in our discretion) and Universal Service Fees ("USF") or similarly imposed charges (the amount or method of calculation of these fees may change at any time without notice to you) except to the extent prohibited by law. Regulatory and administrative fees and USF are not taxes or government required charges. We may impose regulatory and administrative fees whether or not all or some services are used, or available to you, or in your location. We are required to use the residential or business street address you provided us to determine certain Taxes & Fees. If you give us an address (such as a PO box) that is not a recognized street address, does not identify the taxing jurisdictions applicable to the address or does not reflect the service area associated with your Number, you may be assigned a default location for Taxes & Fees calculation, which may result in a higher or lower charge for certain Taxes & Fees and you have 60 days from the date of the first bill that contains disputed Taxes & Fees to notify us or you waive your right to dispute those Taxes & Fees.</strong></li></p>

							<p><li><strong><u>Disclaimer of Warranties.</u></strong> EXCEPT FOR ANY OTHER WRITTEN WARRANTY THAT MAY BE PROVIDED, AND TO THE EXTENT PERMITTED BY LAW, ALL SERVICES, PRODUCTS AND THIRD PARTY PRODUCTS ARE PROVIDED "AS IS," "WITH ALL FAULTS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMIT, WARRANTIES OF TITLE, MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. YOU ASSUME ALL RESPONSIBILITY AND RISK FOR USE OF THE SERVICE OR PRODUCTS. WE DO NOT AUTHORIZE ANYONE TO MAKE A WARRANTY OF ANY KIND ON OUR BEHALF, AND YOU SHOULD NOT RELY ON ANY SUCH STATEMENT. ANY STATEMENTS MADE IN PACKAGING, MANUALS OR OTHER DOCUMENTS, OR BY ANY OF OUR DEALERS (EXCEPT FOR ANY WRITTEN LIMITED WARRANTY THAT MAY BE PROVIDED), ARE FOR INFORMATIONAL PURPOSES ONLY AND ARE NOT WARRANTIES BY US OF ANY KIND. WE AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, DEALERS, SUPPLIERS, PARENTS, SUBSIDIARIES OR AFFILIATES ("T-MOBILE AFFILIATES") DO NOT WARRANT THAT THE INFORMATION, SOFTWARE, PRODUCTS, PROCESSES, OR SERVICES WILL BE UNINTERRUPTED, ACCURATE, COMPLETE, USEFUL, FUNCTIONAL, BUG OR ERROR FREE. IF YOU RECEIVED A WRITTEN "T-MOBILE LIMITED WARRANTY" WITH YOUR PHONE, IT IS THE ONLY WARRANTY MADE BY US WITH RESPECT TO THE PHONE. IF APPLICABLE STATE LAW DOES NOT ALLOW THE DISCLAIMER OF CERTAIN IMPLIED WARRANTIES, THE RELEVANT PORTIONS OF THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</li></p>

							<p><li><strong><u>Limitation of Liability.</u> We are not liable to you, other users of your Phone or third parties for any deficiency in performance or quality, caused in whole or in part by an act or omission of an underlying carrier or service provider, website, messaging community, dealer, equipment or facility failure, Phone failure or unavailability, discontinuation of Service, or Phones, network problems, lack of coverage or network capacity, equipment or facility upgrade or modification, delay or failure of number portability, acts of God, strikes, fire, terrorism, war, riot, emergency, government actions, equipment or facility shortage or relocation, the failure of an incoming or outgoing call, including 9-1-1 emergency, priority access, or secured service call, to be connected or completed or for the functionality of location services, including 9-1-1 location services, priority access, or secured call or alert service, or causes beyond our reasonable control.</strong> EVEN IF T-MOBILE HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES, T-MOBILE AND T-MOBILE AFFILIATES WILL NOT BE LIABLE TO YOU OR ANY OF YOUR EMPLOYEES, AGENTS, CUSTOMERS OR ANY THIRD PARTIES FOR ANY DAMAGES ARISING FROM USE OF THE SERVICE OR ANY PHONE, INCLUDING WITHOUT LIMITATION: PUNITIVE, EXEMPLARY, INCIDENTAL, TREBLE, SPECIAL OR CONSEQUENTIAL DAMAGES; LOSS OF PRIVACY OR SECURITY DAMAGES; PERSONAL INJURY OR PROPERTY DAMAGES; COPYRIGHT, TRADEMARK, PATENT, TRADE SECRET OR OTHER INTELLECTUAL PROPERTY DAMAGES; OR ANY DAMAGES WHATSOEVER ARISING FROM INTERRUPTION OR FAILURE OF SERVICE, LISTING ERRORS, LOST PROFITS, LOSS OF BUSINESS, LOSS OF DATA, LOSS DUE TO UNAUTHORIZED ACCESS OR DUE TO VIRUSES OR OTHER HARMFUL COMPONENTS, COST OF REPLACEMENT PRODUCTS AND SERVICES, SUSPENSION, TERMINATION, OR THE INABILITY TO USE THE SERVICE OR ANY PRODUCT, THE CONTENT OF ANY DATA TRANSMISSION, COMMUNICATION OR MESSAGE TRANSMITTED TO OR RECEIVED BY YOUR PHONE (WHETHER READ OR UNREAD, SOLICITED OR UNSOLICITED), OR LOSSES RESULTING FROM ANY PRODUCTS, GOODS OR SERVICE PURCHASED, MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH THE SERVICE. IF THE STATE LAW APPLICABLE TO YOUR CLAIMS DOES NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, OR OTHER MODIFICATIONS OF OR LIMITATIONS TO CERTAIN REMEDIES, THE RELEVANT PORTIONS OF THE ABOVE EXCLUSION OR LIMITATION WILL NOT APPLY TO YOU.</p>

							<p>THE MAXIMUM AGGREGATE LIABILITY OF T-MOBILE AND T-MOBILE AFFILIATES TO YOU, AND THE EXCLUSIVE REMEDY AVAILABLE IN CONNECTION WITH THE AGREEMENT FOR ANY AND ALL DAMAGES, INJURY OR LOSSES ARISING FROM ANY AND ALL CLAIMS OR CAUSES OF ACTION RELATED TO SERVICES OR PHONES, SHALL BE A REFUND OR REBATE OF THE PRORATED MONTHLY OR OTHER CHARGES YOU PAID OR OWE US FOR THE APPLICABLE SERVICE OR PHONE. THE EXISTENCE OF MULTIPLE CLAIMS OR SUITS UNDER OR RELATED TO THIS AGREEMENT WILL NOT ENLARGE OR EXTEND THE LIMITATION OF MONEY DAMAGES. <strong>EXCEPT TO THE EXTENT PROHIBITED BY LAW, ALL CLAIMS MUST BE BROUGHT WITHIN 2 YEARS OF THE DATE THE CLAIM ARISES.</strong></li></p>

							<p><li><strong><u>Indemnification.</u></strong> You agree to defend, indemnify and hold us, T-Mobile Affiliates and any roaming or network partner harmless from any and all claims, demands, actions, liabilities, costs or damages arising out of your use of the Service or Products, any legal disclosures we make relating to your Service or Product, or your breach of this Agreement. You further agree to pay our reasonable attorneys\' and expert witnesses\' fees and costs arising from any actions or claims by third parties and those incurred in establishing whether this Sec. 15 applies.</li></p>

							<p><li><strong><u>Privacy.</u></strong> Wireless systems use radios to transmit communications over a complex network. We do not guarantee that your communications using the Service or Products will be private or secure, and we are not liable to you for any lack of privacy or security you may experience. You are responsible for taking precautions and providing security measures best suited for your situation and intended use of the Service. <strong>We may (but are not required to) monitor, intercept, and disclose your transmissions, location or communications and may disclose your billing, account, calling records, or other information, in good faith reliance on legal process, if required by law or to protect our rights, business, network or customers. We may locate you through our network. Your caller identification (such as your name and Number) even if unlisted may be displayed to others (for example, on the equipment or bill of the person receiving your call or any Internet site you visit.)</strong> We may list your name, address, and Number in a published directory with your consent. For more information on our privacy policies, please see our privacy notice at www.t-mobile.com/ privacy. The way third parties handle and use your personal information is governed by their policies and we are not responsible for their policies, or their compliance with them.</li></p>

							<p><li><strong><u>Lost or Stolen Phone.</u></strong> If your Phone is lost or stolen ("Lost Phone") you will not be liable for unauthorized airtime charges incurred on the Lost Phone if you: (a) notify us immediately; (b) ask us to deactivate the Lost Phone; and (c) provide within 14 days any documentation we request, including a police report. <strong>You must fulfill the remainder of your Term by activating a replacement Phone (which may be full price) or the cancellation fee will apply.</strong></li></p>

							<p><li><strong><u>Number Portability.</u></strong> You may be able to transfer your Number to another wireless carrier or to bring your number to us. For information about Number Portability, please visit www.t-mobile.com or contact Customer Care at (800) 937-8997 or 611 from your Phone. You may not transfer your Number if your account has been cancelled or suspended, or prepaid account expired. <strong>You remain liable for charges incurred resulting from your Service with us or service with your former carrier, including cancellation fees. If you call 911 after you request a transfer, but before you receive confirmation of completion, the 911 operator may not have accurate information on your identity and location. You must inform the 911 operator of your identity and location immediately upon placing the call.</strong></li></p>

							<p><li><strong><u>Assignment.</u></strong> We may assign all or part of our rights or duties under the Agreement without such assignment being considered a change to the Agreement, and without notice to you, except to the extent provided by law. We are then released from all liability. You may not assign the Agreement without our prior written consent. Subject to these restrictions, the Agreement will bind the heirs, successors, subcontractors, and assigns of the respective parties, who will receive its benefits.</li></p>

							<p><li><strong><u>Notices/Customer Communications.</u></strong> We may send you written notice, which may be on or included with your bill, which is considered given and received by you on the third day after the date deposited in the U.S. Mail to your address in our billing records. You agree we may also notify and communicate with you, or respond to your inquiries electronically through your Phone or otherwise, such as by e-mail, voicemail or text messaging, which is considered given and received immediately upon transmission. Written notice to us is considered given when received by our registered agent, Corporation Services Company ("CSC") 1010 Union Ave. SE, Olympia, WA 98501.</li></p>

							<p><li><strong><u>Digital Millennium Copyright Act ("DMCA") Notice.</u></strong> To the extent in providing Service we may act as a "services provider" (as defined by DMCA) and offer services as online provider of materials and links to third-party sites. As a result, third-party materials that we do not own or control may be transmitted, stored, accessed or made available using the Service. If you believe material available via the Service infringes a copyright, notify us using the notice procedure under the DMCA. We will respond expeditiously to remove or disable access to such material and will follow the procedures specified in the DMCA to resolve the claim. Our designated agent to whom you must address infringement notices under the DMCA is CSC (see Sec. 20).</li></p>

							<p><li><strong><u>Severability and Survivability.</u></strong> Except to the extent expressly set forth in Sec. 2, all terms and conditions of these T&C\'s are independent of each other and if any provision of these T&C\'s is held to be inapplicable or unenforceable, then (a) that term or provision shall be construed, as nearly as possible, to reflect the intentions of the parties with the other terms or provisions remaining in full force and effect, (b) the T&C\'s will not fail their essential purpose and (c) the balance of the T&C\'s remain unaffected and in full force and effect, unless our obligations are materially impaired, in which event we have the right to terminate the Agreement. You and we will continue to be bound by the following Secs. (and any other provisions or rights and obligations that may reasonably be construed as surviving) of these T&C\'s after the Agreement ends, regardless of reason: 2-6, 10-15, 18, 19, 20, 22, 23, 25 and 26.</li></p>

							<p><li><strong><u>Entire Agreement/Applicable Law/Venue/Miscellaneous.</u></strong> This Agreement represents the final and entire agreement between you and us regarding the Service and Products. Electronic images of the Agreement will be considered originals. You acknowledge that you have not relied on any other representations not specifically included in this Agreement. If we don\'t enforce our rights under any of the provisions of the Agreement, we may still require strict compliance in the future. You represent that you are of legal age and have the legal capacity to enter into this Agreement. If you are contracting on behalf of a company, you represent that you are authorized to enter into this Agreement and agree to be personally liable for all accounts if you are not so authorized. <strong>This Agreement is governed by the Federal Arbitration Agreement, applicable federal law, and the laws of the state in which your billing address in our records is located. Foreign laws do not apply. Arbitration proceedings or any actions to enforce an arbitration award must be in the state where your Service is principally provided, but not outside the U.S.</strong></li></p>

							<p><li><strong><u>Additional Terms for Prepaid Customers.</u></strong> You are responsible for prepaying all charges for using the Service. The airtime balance in your prepaid account is reduced by the charges attributable to your use of the Service. Service lasts as long as the earlier of a) the time period on a prepaid card or coupon or b) when the airtime balance goes to zero, then Service will be interrupted. You may continue to use Service by purchasing additional prepaid Service. If your account expires, you may lose your Number. You will not receive a monthly bill or activity record. <strong>Prepaid Service is non-refundable (even if returned during the return period), and no refunds or other compensation will be given for unused airtime balances, lost or stolen prepaid cards or coupons. Applicable Taxes & Fees will be included in your prepaid charges.</strong></li></p>

							<p><li><strong><u>Additional Terms for SmartAccess Customers.</u></strong> SmartAccess is subject to credit eligibility, determined in our discretion. We may suspend Service to any Number without prior notice if your account balance exceeds your spending limit or you are late with a payment (whether or not you exceed your spending limit). If we suspend Service because your balance exceeds your spending limit, we may, in our sole discretion, reinstate Service after you make a payment that reduces your account balance and your account is not in arrears. If we suspend Service because you are late with payment, we may, in our sole discretion, reinstate Service if you pay the entire balance owing on your account. Regardless of suspension, you will be liable for all charges for Service under the Agreement, including monthly Service and usage charges, and other charges or purchases billed to your account, whether or not you reinstate Service. SmartAccess customers are only eligible for select rate plans. Smart Access activation fees are non-refundable unless you: (a) purchased the Phone and Service directly from a T-Mobile store, www.t-mobile.com or (800) TMOBILE; and (b) cancel Service and return the Phone to the place of purchase in accordance with Sec. 5.</li></p>

							<p><li><strong><u>Other Agreements or Warranties.</u></strong> Other Services (such as T-Mobile HotSpot or Equipment Protection) or Products may come with separate written terms or conditions, and warranties that govern their use or purchase. Please see those other agreements or warranties for your rights and duties regarding their use.</li></p>
						</ol>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="right" class="bodyBlack">
						<a href="?sec=terms&terms=rebates&zipcode='.$zipcode.'" class="bodyBlack">Rebate Terms & Conditions</a> | <a href="?sec=terms&terms=mi&zipcode='.$zipcode.'" class="bodyBlack">Mobile Intentions Terms & Conditions</a>
					</td>
				</tr>
				</table>
					';
				// Rebate Terms
				}elseif ($terms == "rebates"){
					echo'
				<table width="100%">
				<tr>
					<td class="bigBlack"><strong><u>Rebate Terms & Conditions:</u></strong></td>
					<td align="right" class="bodyBlack">
						<a href="?sec=terms&terms=mi&zipcode='.$zipcode.'" class="bodyBlack">Mobile Intentions Terms & Conditions</a> | <a href="?sec=terms&terms=tmobile&zipcode='.$zipcode.'" class="bodyBlack">T-Mobile Terms & Conditions</a>
					</td>
				</tr>
				<tr>
					<td colspan="2" class="bodyBlack"><br>
						<p class="bodyBlack"><strong>Rebates are dependent on the rate plan chosen and the following criteria described as follows:</strong></p>
						<ul>
							<p><li>Customer is only eligible for a rebate on every device that the wireless Carrier has approved their credit for that does not require a deposit or spending limit.</li></p>

							<p><li>All rebates require an activation of a voice plan $39.99 or higher and data devices require an activation of a $39.99 or higher voice plan and an unlimited data plan to be eligible.</li></p>

							<p><li>The amount of the rebate cannot exceed the cost of the device on customer\'s first bill or equipment invoice.</li></p>

							<p><li>A rebate form must be submitted for each device separately and we suggest making copies for your records. You must submit the completed and signed rebate form with a copy of your first invoice clearly showing the amount you were charged for your equipment and your first bill (may be the same document in some instances).</li></p>

							<p><li>Mail copies to the address on the rebate form. All rebates will be processed on the 30th day from the original activation date. Please allow 6 to 8 weeks to receive your rebate check following the 30th day. <em>Note: Your rebate check will never exceed the actual cost of your equipment listed on your "Equipment Invoice" or "Wireless Carrier Bill".</em></li></p>

							<p><li>Mail-In Rebates are only available for all NEW Line of service and not eligible for Migrations, Upgrades and Contract Renewals.</li></p>
						</ul>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="right" class="bodyBlack">
						<a href="?sec=terms&terms=mi&zipcode='.$zipcode.'" class="bodyBlack">Mobile Intentions Terms & Conditions</a> | <a href="?sec=terms&terms=tmobile&zipcode='.$zipcode.'" class="bodyBlack">T-Mobile Terms & Conditions</a>
					</td>
				</tr>
				</table>
					';
				};
				?>
			</td>
		</tr>
		</table>
		<img src="images/spacer.gif" alt="" width="1" height="12" border="0"><br>
	</td>
	<!-- Right border -->
	<td width="2" bgcolor="#E20074">
		<img src="images/spacer.gif" alt="" width="2" height="2" border="0">
	</td>
</tr>
<tr>
	<!-- Footer -->
	<td width="100%" height="15" colspan="3" bgcolor="#E20074" class="smallWhite">
		<img src="images/spacer.gif" alt="" width="1" height="15" border="0">
	</td>
</tr>
</table>

<!-- END Include terms.php -->	
