<style>body {font-family:Arial,Helvetica,sans-serif; font-size:12px; color:#000000; text-decoration:none;}</style>

<p><strong>IMPORTANT SERVICE/PRODUCT SPECIFIC TERMS</strong></p>
			
<p>Your Agreement with Sprint PCS Service and includes the terms of your service plan and the attached Sprint PCS Terms and Conditions of Service ("Ts and Cs") - carefully read all these terms which include, among other things, a MANDATORY ARBITRATION of disputes provision. For certain optional provisions that may not be referenced here, the Agreement also includes terms relating to those services that are set forth at www.sprint.com or in our store brochures.</p>
			
<p><strong>Term Agreements:</strong> If your Agreement requires you to keep a phone active/maintain a line of service for a minimum Term, the Term begins on the phone activation date; for customers changing service plans, the Term begins when the new service plan is selected. You may terminate any line of service before its Term ends by calling *2, however you will be responsible for an EARLY TERMINATION FEE of up to $200 ("Fee") for each line of service terminated early. You do not have to pay the Fee if you terminate under our return policy or where the Ts and Cs allow you to do so without the Fee. Payment of the Fee does not satisfy other outstanding obligations owed to us, including maintaining Term Commitments on other lines of service, or service or equipment-related charges.</p>
			
<p><strong>Service Provisions:</strong> Service plans, customizable/upgrade options and special offers may not be available everywhere or combinable with certain other promotions/options. Coverage is not available everywhere. See our mapping brochure for approximate outdoor coverage information. Sprint PCS Service Plans are subject to credit approval. Rates exclude taxes, and Sprint Fees such as a USF charge that varies quarterly, cost recovery fees $0.55 per line, and state/local fees that vary by area (in some areas up to 15% but in most instances less than 2%). Call 1-866-770-6690 for the up-to-date amount of the USF charge and information on cost recovery charges. A $36 phone activation fee applies to new activations, certain service plan changes or upgrades of equipment. A deposit of up to $500 may be required to establish service. Service requires a phone compatible with our network. Monthly service charges are not refundable if service is terminated before your billing cycle ends.</p>
			
<p><strong>Basic Services:</strong> All phone usage, including incoming and outgoing calls, incur charges unless specified otherwise by plan type. Unused plan minutes do not carry forward. Except with certain plans, included plan minutes are not good for local or long-distance off-network roaming calls. International roaming rates will vary. On a call that crosses time periods, minutes are deducted or charged based on the call start time. Calls are rounded up to the next whole minute.</p>
			
<p><strong>Sprint PCS Vision Services:</strong> Services require a Sprint PCS Vision Phone or device and are not available while roaming off the nationwide Sprint PCS network. Data usage is calculated on a per kilobyte basis and is rounded up to the next whole kilobyte. Rounding occurs at the end of each session or each clock hour and, at that time, we will deduct accumulated data usage from your plan, or assess overage or casual usage charges. You are responsible for all data activity from and to your phone/device, regardless of who initiates the activity. Estimates of data usage will vary from actual use. In certain instances, we may delete premium and non-premium items downloaded to available storage areas (e.g., personal vault), including any pictures, games, ringers or screen savers. Your invoice will not separately identify the number of kilobytes attributable to your use of specific sites, sessions or services used. Premium services (games, ringers, etc.) priced separately.</p>
			
<p><strong>PROMOTIONS, OPTIONS AND OTHER PROVISIONS</strong></p>
			
<p><strong>Sprint PCS Vision:</strong> Not available where use is in connection with server devices or host computer applications, other systems that drive continuous heavy traffic or data sessions, or as substitutes for private lines or frame relay connections. Sprint PCS Vision Packs are not available: (1) with any other device used in connection with a computer or PDA - including phones, smart phones or other devices used with connection kits or similar phone-to-computer/PDA accessories; and (2) with Bluetooth Sprint PCS Vision Phones used as a modem in connection with other devices. Sprint reserves the right to deny or to terminate service without notice for any misuse. Credits for Premium Services do not carry forward and are not available for use with all services. Sprint PCS Vision -Data Usage Only is available for use with connection cards and PDAs, but is not available for use with Blackberry devices.</p>
			
<p><strong>Roaming-Included Plans:</strong> Not available with single-band or digital mode only phones, or to customers residing in an area not covered by the nationwide Sprint PCS network. Sprint may terminate service if a majority of minutes in a given month are used while roaming off the nationwide Sprint PCS network. International calling including in Canada & Mexico, not included. Usage in Expanded Voice Coverage areas may, in some instances, be invoiced after 30-60 days. When calling from Expanded Voice Coverage Areas: (a) Sprint PCS Vision and Sprint PCS to PCS Calling services are not available; and (b) certain calling features (Voicemail, Caller ID, Call Waiting, etc.) may not work.</p>
			
<p><strong>Sprint PCS Add-a-Phone:</strong> Requires a minimum two-year Term agreement for each phone/line of service added ("Secondary Line"). The first phone activated on the service plan ("Primary Line") and Secondary Lines may have different Term commitment end dates. If the Primary Line on the account is terminated prior to the expiration of the Term of any Secondary Line, a Secondary Line must move to the Primary Line position.</p>
			
<p><strong>Sprint Mobile-to-Mobile:</strong> Sprint Mobile to Mobile is only available on calls placed directly between separate Sprint PCS Phones and most Nextel Phones while on the nationwide Sprint PCS network (not through Voicemail, Directory Assistance or other indirect methods). Excludes Nextel subscribers in certain markets. Sprint Mobile to Mobile is not available while roaming.</p>
			
<p><strong>SMS Messaging:</strong> Unused plan messages do not carry forward. Premium SMS Messages are an additional charge and vary by product. International rates may vary.</p>
			
<p><strong>Sprint Voice Command:</strong> Not available while roaming off the nationwide Sprint PCS network. Calls to 911 or similar emergency numbers cannot be placed through Sprint PCS Voice Command. Dial "911" on your phone in an emergency. Airtime and applicable long-distance charges begin when you press or activate the TALK or similar key.</p>
			
<p><strong>Sprint Total Equipment Protection:</strong> The Sprint Equipment Replacement Program is insurance underwritten by Continental Casualty Company, a CNA company (CNA) and administered by lock\line, LLC (lock\line Insurance Agency, LLC CA Lic.#oD63161), a licensed agent of CNA. There is a $50 deductible per approved insurance replacement. Sprint Equipment Service and Repair Program is administered by lock\line Warranty Services, LLC or one of its affiliates. See a Sprint PCS Total Equipment Protection brochure for complete terms and conditions of coverage, available at www.sprint.com or any participating Sprint location.</p>
			
<p><strong>Roadside Rescue:</strong> Must be with vehicle and have your Sprint PCS Phone with you at the time of service. Limit 4 calls per program year (starts when service is added to your account). Allow approximately 72 hours to provision service to your account. Covers light passenger cars & trucks. Excludes RVs, motorcycles, boats, trailers, limousines, taxis and commercial or heavy-duty vehicles. This is not a reimbursement service and is not valid when operating vehicle off-road. Services are provided by AAA, AAA clubs, CAA clubs and in California, the National Automobile Club and Auto Partners Motor Club, Inc. Sprint is not a motor club.</p>
			
<p><strong>Sprint PCS International and Sprint PCS Call Canada:</strong> For verification purposes, activation of plan may take approximately 1 to 3 days, additional information may be required during verification process.</p>
			
<p><strong>One Month Free Offers:</strong> If you do not wish to continue with the service after the initial free month, you must contact us prior to the billing end date of your second invoice to avoid charges. Additional charges apply for premium content.</p>
			
<p><strong>Sprint 30-day Risk-Free Guarantee:</strong> We will refund any activation fee you paid and waive your early termination fee only if, within 30 days of activation, you: (1) return your complete, undamaged Sprint PCS Phone with the original retailer's proof of purchase; and (2) request that we deactivate your service. In all instances, you are responsible for all charges based on actual usage (partial monthly service charges, taxes and Sprint surcharges or fees). Accessories may be returned within 30 days of purchase.</p>
			
<p><strong>Sprint Spending Limit Program:</strong> In most instances a deposit between $125 and $500 applies. We may require a deposit of up to $1000 in certain instances. A preset account spending limit of between $125 and $500 will apply - ask the specific amount. We may limit the number of phones you can activate on your account. Monthly service plan charges accrue even if your service is turned off, when you exceed your spending limit or in instances of nonpayment. Roaming usage may be invoiced after 30 - 60 days.</p>
			
<p>&copy;2005 Sprint-Nextel. All rights reserved. SPRINT, the "Going Forward" logo, the NEXTEL name and logo, and other trademarks are trademarks of Sprint-Nextel.</p>
