<!-- BEGIN Include terms.php -->

<div id="termsOfUse">
	<div id="termsHeadline">Web Site Terms of Use</div>
	<div id="termsTagline">Effective: 11/11/2011</div>
	<div id="termsText">
		<p>Welcome to the <em>Prayer Belts</em> Web site (this "Web Site"). <em>Prayer Belts, Inc.</em> provides this Web Site subject to the following terms of use (these "Terms"). These Terms explain a contractual agreement between you ( "User," "You," "Your") and <em>Prayer Belts, Inc.</em> ( "We," "Us," "Our") regarding Your use of this Web Site. You should print a copy of these Terms for Your records. Please note, however, that We may update and amend these Terms from time to time.</p>

		<p><span class="termsHeader">What You Should Know</span><br><br>
		The goal of this Web Site is to provide You with access to information about our facilities, services, products, and related links to meet Your needs (the "Content"). The Terms are meant to protect all of our visitors to this Web Site, and Your access to and use of this Web Site signifies Your agreement with these Terms. DO NOT USE THIS WEB SITE IF YOU DO NOT AGREE WITH THESE TERMS. We reserve the right, in our sole discretion, to modify, alter or otherwise update these Terms at any time. Such modifications, alterations, and updates shall be effective immediately upon posting. You agree to be bound by such modified, altered, and updated Terms if You access or use this Web Site after We have posted notice of such modifications, alterations or updates.</p>

		<p>Consistent with our goals, this Web Site may permit You to link to many other Web sites that may or may not be affiliated with this Web Site and/or with Us. The other linked Web sites have different terms of use that are not the same as these Terms. Your access to and use of such linked Web sites through links provided on this Web Site is governed by the terms of use and policies of those sites, not this Web Site.</p>

		<p><span class="termsHeader">Privacy</span><br><br>
		Sales data and certain other information about You is subject to Our <a href="?sec=privacy">Privacy Policy</a>. For more information, please review Our <a href="?sec-privacy">Privacy Policy</a>.</p>

		<p><span class="termsHeader">Use of This Web Site</span><br><br>
		We control and operate this Web Site. All Content on this Web Site, including, but not limited to, text, photographs, images, illustrations, audio clips, and video clips, is protected by copyrights, trademarks, service marks, and/or other intellectual property rights (which are governed by United States and worldwide copyright laws and treaty provisions, privacy and publicity laws, and communication regulations and statutes). The Content is owned and controlled by Us or Our affiliates, or by third party content providers, merchants, sponsors and licensors (collectively the "Providers") that have licensed their content or the right to market their products and/or services to Us. Content on this Web Site or any Web site owned, operated, licensed or controlled by the Providers is solely for Your personal, non-commercial use. You agree to abide by all additional copyright notices, information, or restrictions contained in any Content. You may download a single copy of any Content contained on this Web Site, solely for Your personal, non-commercial Use, consistent with these Terms, provided that You maintain all copyright and other notices contained in such Content.</p>

		<p>You may not copy, reproduce, republish, upload, post, transmit, distribute, and/or exploit the Content in any way (including by e-mail or other electronic means) for commercial use without the prior written consent of Us or the Providers. You may request consent by mailing your request to <em>Prayer Belts, Inc.</em>, 5100 Eldorado Parkway, Suite 102, #903, McKinney, Texas, 75070. Your modification of the Content, use of the Content on any other Web site or networked computer environment, or use of the Content for any purpose other than personal, non-commercial use, without the prior written consent of Us or the Providers, violates the intellectual property rights and proprietary rights of the Content owners and is prohibited.</p>

		<p>You may not use on Your Web site any registered or unregistered trademarks, service marks or copyrighted materials appearing on this Web Site, including but not limited to any logos or characters, without the express written consent of the owner of the mark or copyright. You may not frame, deep link, or otherwise incorporate into another Web site any of the Content or other materials on this Web Site without Our express prior written consent.</p>

		<p>Violation of trademark and copyright laws may result in significant civil liability or criminal penalties under United States and/or worldwide copyright and trademark laws. You recognize that any reproduction or use of Content, except as authorized by these Terms, is considered intentional infringement.</p>

		<p><span class="termsHeader">User's Responsibilities</span><br><br>
		You warrant and represent to Us that You will not use this Web Site for any purpose that is unlawful or prohibited by these Terms, including without limitation the posting or transmitting any threatening, libelous, defamatory, obscene, scandalous, inflammatory, pornographic, or profane material. If You violate any of these Terms, Your permission to use this Web Site immediately terminates without the necessity of any notice. We retain the right to deny access to anyone at Our discretion for any reason, including for violation of these Terms.</p>

		<p>You are solely responsible for Your Information, and We act as a passive conduit for Your online distribution and publication of Your Information. As used in these Terms, "Information" means any information or data that You submit to this Web Site and any information or data that is generated by this Web Site as a result of Your use of this Web Site.</p>

		<p>In the event that You are provided with User identification numbers or codes (collectively, " ID's"), confirmation numbers, and/or passwords (as applicable) in the use of this Web Site, You shall maintain such User ID's, confirmation numbers, and/or passwords in confidence and You agree not to distribute or disclose the same to third parties. It is Your responsibility to notify Us if We need to change or discontinue any of Your ID's, confirmation numbers, or passwords. It is also Your responsibility to immediately request discontinuation of an ID, confirmation number, or password upon Your knowledge or belief that such ID, confirmation number, and/or password is, or may be subject to, a breach of confidentiality. We may suspend or terminate Your service or access to this Web Site if We believe a breach of these Terms has occurred.</p>

		<p>You agree to provide true, accurate, current and complete Information. If You provide any Information that is untrue, inaccurate, not current or incomplete (or We have reasonable grounds to suspect that such Information is untrue, inaccurate, not current or incomplete), We have the right to suspend or terminate Your access and activity, and refuse any and all current or future use of this Web Site.</p>

		<p><span class="termsHeader">Prohibited Activities</span><br><br>
		You are specifically prohibited from any use of this Web Site, and You agree not to use or permit others to use this Web Site, if you: (a) take any action that imposes an unreasonable or disproportionately large load on the Web Site's infrastructure, including but not limited to "spam" or other such unsolicited mass e-mailing techniques; (b) disclose to, or share with, the assigned confirmation numbers and/or passwords with any unauthorized third parties or using the assigned confirmation numbers and/or passwords for any unauthorized purpose; (c) attempt to decipher, decompile, disassemble or reverse engineer any of the software or HTML code comprising or in any way making up a part of this Web Site; (d) upload, post, emailing or otherwise transmitting any Information, Content, or proprietary rights that You do not have a right to transmit under any law or under contractual or fiduciary relationships; (e) violate any applicable local, state, national or international law, including, but not limited to, any regulations having the force of law; and, (f) use any robot, spider, intelligent agent, other automatic device, or manual process to search, monitor or copy Our Web pages, or the Content without Our prior written permission, provided that generally available third party Web browsers such as Mozilla Firefox&reg;, Google Chrome&reg;, and Microsoft Internet Explorer&reg; may be used without such permission.</p>

		<p><span class="termsHeader">Information Posted to Web Site</span><br><br>
		With respect to all Information You elect to post to publicly accessible areas of the Web Site, You agree that We have the right to use, reproduce, modify, publish, perform and display such Information (in whole or part) worldwide; provided that such use is subject to the terms of Our Privacy Policy.</p>

		<p>You acknowledge and agree that We may preserve Information and may also disclose Information if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the Terms; (c) respond to claims that any Information violates the rights of third parties; or (d) protect the rights, property, or personal safety of Our business, employees, Providers, affiliates, users, and/or the public.</p>

		<p><span class="termsHeader">Links to Other Web Sites</span><br><br>
		This Web Site may contain links to third party and/or other affiliated Web sites not under Our control or operation (the "Linked Sites"). The links will let You leave this Web Site, and You access them at Your own risk. You acknowledge that We provide the Linked Sites for Your convenience and information only. We do not endorse nor are We responsible for any content, information, or other related materials found at any such Linked Sites or any links contained within such Linked Sites, whether or not We are affiliated with the owners of such Linked Sites. Moreover, We do not control any use of content, information or other related material that You provide to, or is collected and/or tracked by, such Linked Sites. Such use by Linked Sites is governed by the terms of use statements and/or privacy policies of such Linked Sites, not this Web Site, and as a result may differ from Ours. You may not establish a hyperlink to this Web Site or provide any links that state or imply any sponsorship or endorsement of Your Web site by Us or the Providers.</p>

		<p><span class="termsHeader">Dealings with Advertisers</span><br><br>
		Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through this Web Site, including payment and delivery of related goods or services, and any other terms, conditions, warranties, or representations associated with such dealings are solely between You and such advertiser. You agree that We (and the Providers) shall neither be responsible nor liable for any loss or damage incurred by You as the result of any such dealings or as the result of the presence of such advertisers on this Web Site.</p>

		<p><span class="termsHeader">NO WARRANTIES</span><br><br>
		ALL CONTENT ON THIS WEB SITE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. OTHER THAN THOSE WARRANTIES WHICH, UNDER THE U.S. LAWS APPLICABLE TO THESE TERMS, ARE IMPLIED BY LAW AND ARE INCAPABLE OF EXCLUSION, RESTRICTION, OR MODIFICATION, WE DISCLAIM ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</p>

		<p>NEITHER WE, OUR AFFILIATED OR RELATED ENTITIES, NOR THE PROVIDERS, NOR ANY PERSON INVOLVED IN THE CREATION, PRODUCTION, AND DISTRIBUTION OF THIS WEB SITE, WARRANT THAT THE FUNCTIONS CONTAINED IN THIS WEB SITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVER THAT MAKES THE CONTENT AVAILABLE WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE CONTENT THAT YOU ACCESS ON THIS WEB SITE IS PROVIDED SOLELY FOR YOUR CONVENIENCE AND INFORMATION ONLY. WE DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THIS WEB SITE, OR AS TO THE RELIABILITY, ACCURACY, USEFULNESS, OR CURRENCY OF ANY CONTENT, SERVICE, AND/OR MERCHANDISE ACQUIRED PURSUANT TO YOUR USE OF THIS WEB SITE.</p>

		<p>YOU USE THIS WEB SITE AT YOUR OWN RISK. YOU (AND NOT US) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING (INCLUDING WITHOUT LIMITATION YOUR INTERNET CONNECTION) AND REPAIR OR CORRECTION OF YOUR SYSTEM.</p>

		<p><span class="termsHeader">LIMITATION OF LIABILITY</span><br><br>
		IN NO EVENT SHALL WE NOR OUR AFFILIATED OR RELATED ENTITIES (INCLUDING PROVIDERS), NOR ANY OF OUR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS, NOR ANY PERSON OR ENTITY INVOLVED IN THE CREATION, PRODUCTION AND DISTRIBUTION OF THIS WEB SITE, BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES WHETHER ARISING UNDER CONTRACT, WARRANTY, OR TORT (INCLUDING NEGLIGENCE) OR ANY OTHER THEORY OF LIABILITY, REGARDLESS OF WHETHER WE KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING WITHOUT LIMITATION FROM THE USE OR ATTEMPTED USE OF THIS WEB SITE OR ANY OTHER LINKED SITE.</p>

		<p>OUR LIABILITY, AND THE LIABILITY OF OUR PROVIDERS, TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE LESSER OF (A) THE AMOUNT OF FEES YOU PAY TO US IN THE 12 MONTHS PRIOR TO THE ACTION GIVING RISE TO LIABILITY, OR (B) $500. Some states do not allow for the limitation of liability, so the foregoing limitation may not apply to You.</p>

		<p>BY WAY OF EXAMPLE ONLY, WE AND RELATED PERSONS AND ENTITIES SHALL NOT BE RESPONSIBLE OR LIABLE FOR ANY CLAIM OR DAMAGE ARISING FROM: FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION, COMPUTER VIRUS, THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO OR ALTERATION OF PERSONAL RECORDS, OR THE RELIANCE UPON OR USE OF CONTENT, INFORMATION, OPINIONS OR OTHER MATERIALS APPEARING ON THIS WEB SITE. MOREOVER, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT WE ARE NOT LIABLE OR RESPONSIBLE FOR ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD PARTIES.</p>

		The limitation of liability reflects the allocation of risk between the parties. The limitations specified in this Section will survive and apply even if any limited remedy specified in these Terms is found to have failed of its essential purpose. The limitations of liability provided in these Terms insure to the benefit of Us and the Providers, and to all respective officers, directors, employees, representatives, attorneys, and agents.

		<p><span class="termsHeader">Governing Law and Jurisdiction</span><br><br>
		We operate this Web Site (excluding Linked Sites) from Our offices within the State of Texas. It can be accessed from all 50 states, as well as from other countries around the world. As each of these places has laws that may differ from those of Texas, by accessing this Web Site, You agree that these Terms and Your use of the Web Site shall be governed in all respect by the internal substantive laws of the State of Texas, without regard to conflict of laws provisions and shall not be governed by the United Nations Convention on the International Sale of Goods. You further submit to exclusive jurisdiction and venue in the state and federal courts located in the State of Texas for all disputes, cases and controversies regarding this Web Site, Your use of this Web Site, and Your relationship with Us. We make no representation that materials on this Web Site are appropriate or available for use in other locations, and accessing them from territories where the Content is illegal is prohibited. Those who choose to access this Web Site from other locations do so at their own risk and are responsible for compliance with local laws, including laws regarding the transmission of technical data exported from the United States or the country in which You reside.

		<p><span class="termsHeader">Indemnification</span><br><br>
		We reserve the right to report any wrongdoing, if and when We become aware of it, to any applicable government agencies. You agree to indemnify, defend and hold Us and the Providers, Our and their officers, directors, employees, affiliates, agents, licensors, and suppliers harmless from and against any and all claims, demands, actions, costs, liabilities, losses and damages of any kind (including attorneys' fees) resulting from Your use of this Web Site, Your breach of any provision of these Terms and/or any negligent acts, omissions or intentional wrongdoing by You. Any such indemnification shall be conditioned on Our: (a) notifying You in writing of any such claim, demand, action, cost, liability, loss or threat of any thereof; (b) cooperating with You in the defense or settlement thereof; and (c) allowing You to control such defense or settlement. We shall be entitled to participate in such defense at Our own cost and expense.</p>

		<p><span class="termsHeader">Message Boards</span><br><br>
		In the event that We provide message boards or discussion forums on this Web Site (the "Forums"), You agree to use the Forums only in a noncommercial manner. You shall not, without our express approval, distribute or otherwise publish any material containing any solicitation of funds, advertising, or written solicitation for goods and services. You agree that any uploaded materials may be republished without compensation to You or any other person or entity. In addition, You warrant that all moral rights in any uploaded materials have been waived. While We do not and cannot review every message posted by You or any other User in the Forums, and although We are not responsible for these messages, We reserve the right (but not the obligation) to delete, move, or edit messages that We, in our sole discretion, deem abusive, defamatory, obscene, in violation of copyright or trademark laws, or otherwise unacceptable. We do not endorse any Information posted on this Web Site.</p>

		<p>You agree that You must evaluate, and bear all risks associated with, the use of any messages, Information, or Content, including any reliance on the accuracy, completeness, or usefulness of such messages, Information, or Content. In this regard, You acknowledge that You may not rely on any Content We create or information submitted to Us by third parties, including without limitation, information in the Forums, and in all other parts of this Web Site.</p>

		<p><span class="termsHeader">Other General Provisions</span><br><br>
		These Terms are for the benefit of Us and the Providers, Our and their officers, directors, employees, affiliates, agents, licensors, and suppliers. Each of these individuals or entities shall have the right to assert and enforce these Terms directly against You on its (or their own) behalf. Our failure to act with respect to a breach by You or others does not waive Our right to act with respect to subsequent or similar breaches.</p>

		<p>If any provision of these Terms is held to be invalid or unenforceable, such provision will be struck and the remaining provisions enforced. Headings are for reference purposes only.</p>

		<p>The provisions and conditions of these Terms, and each obligation referenced herein, represent the entire Agreement between Us (including the Providers), Our affiliated or related entities, and You, and supersede any prior agreements or understandings not incorporated herein. In the event that any inconsistencies exist between these Terms and any future published terms of use or understanding, the last published Terms shall prevail.</p>

		<p>WE RESERVE ANY RIGHTS NOT EXPRESSLY GRANTED OR STATED IN THESE TERMS.</p>
	</div>
</div>

<!-- END Include terms.php -->
