name#value
str#str
#
demo_mode#0
license#
installed#0
version#
program_name#
default_language#
admin_email#
reporting#1
configuration_overwrite#0
script_path#
script_url#
welcome_display_text#username
require_unique_email#0
time_format#h:i:s
date_format#Y-m-d
time_offset#0
toolbar_default_row1#styleselect,formatselect,fontselect,fontsizeselect,separator,bold,italic,underline,strikethrough,separator,forecolor,backcolor,separator,sub,sup,separator,removeformat
toolbar_default_row2#selectall,cut,copy,paste,pastetext,pasteword,separator,search,replace,separator,undo,redo,separator,bullist,numlist,outdent,indent,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,advhr,charmap
toolbar_default_row3#tablecontrols,separator,anchor,link,unlink,image,separator,visualaid,cleanup,spellchecker,separator,fullscreen,code,help
html_validation_type#allow_all
html_validation_extended_ruleset#
custom_html_validation_ruleset#-a[id|href|title|rel|target],-strong/b,-em/i,-strike,-del,-u,p[class|align|dir],-ol,-ul,-li,br,img[class|src|alt|title|width|height|align],-sub,-sup,-blockquote[dir],-table[border|cellspacing|cellpadding|width|height|class|align|dir],thead[class|rowspan|width|height|align|valign|dir],tr[class|rowspan|width|height|align|valign|dir],th[dir|class|colspan|rowspan|width|height|align|valign|scope],td[dir|class|colspan|rowspan|width|height|align|valign],-div[dir|class|align],-span[class|align],-pre[class],-code[class],-address,-h1[class|align|dir],-h2[class|align|dir],-h3[class|align|dir],-h4[class|align|dir],-h5[class|align|dir],-h6[class|align|dir],hr[class|width|size|noshade],object[classid|codebase|width|height|align],param[name|value],embed[quality|type|pluginspage|width|height|src|align]
whole_file_edit_mode#wysiwyg
enable_gzip_compression#1
link_type#relative
regular_user_privs#acl_only
logout_redirect_url#