<style>
body {font-family:Arial,Helvetica,sans-serif; font-size:12px; color:#000000; text-decoration:none;}
A.body {font-family:Arial,Helvetica,sans-serif; font-size:12px; color:#000000; text-decoration:underline;}
A.body:hover {color:Red; text-decoration:underline;}
A.body:active {color:Red;}
A.body:visited {color:#000000;}
A.body:visited:hover {color:Red; text-decoration:underline;}
</style>

<p><font size="3"><strong>Customer Agreement Terms &amp; Conditions</strong></font></p>

<p><font size="3"><strong>Your Verizon Wireless Customer Agreement</strong></font></p>

<p>Please carefully read this agreement, including the Calling Plan
or Plans you've chosen, before filing it in a safe place.</p>

(Para una copia de este documento en espanol, llame al 1.800.922.0204 o visite a nuestro website a <a href="espanol.vzwshop.com" target="_blank" class="body">espanol.vzwshop.com</a>.)</p>

<p>By accepting this agreement, you're bound by its conditions. It covers important topics such as how long it lasts, fees for early termination and late payments, our rights to change its conditions and your wireless service, limitations of liability, privacy, and settlement of disputes by arbitration instead of in court. If you accept this agreement, it will apply to all your wireless service from us, including all your existing Calling Plans and other lines in service.</p>

<p><font size="3"><strong>Your Calling Plans</strong></font></p>

<p><strong>YOUR CALLING PLANS BECOME PART OF THIS AGREEMENT.</strong> The prices you pay may depend in part on how long-the minimum term-you're agreeing in advance to do business with us. Calling Plans describe these prices and your minimum term. To the extent any condition in your Calling Plan expressly conflicts with this agreement, the condition in your Calling Plan will govern. If at any time you change your service (by accepting a promotion, for example), you'll be subject to any requirements, such as a new minimum term, we set for that change.</p>

<p><font size="3"><strong>Your Rights to Refuse or Cancel This Agreement</strong></font></p>

<p><strong>THIS AGREEMENT STARTS WHEN YOU ACCEPT.</strong> Paragraphs marked &quot;&sect;&quot; continue after it ends. You accept when you do any of the following things after an opportunity to review this agreement:</p>

<ul>
	<li>Give us a written or electronic signature;</li>
	<li>Tell us orally or electronically that you accept;</li>
	<li>Activate your service through your wireless phone;</li>
	<li>Open a package that says you are accepting by opening it; or</li>
	<li>Use your service after making any change or addition when we've told you that the change or addition requires acceptance.</li>
</ul>

<p><strong>IF YOU DON'T WANT TO ACCEPT, DON'T DO ANY OF THESE THINGS.</strong> You can cancel (if you're a new customer) or go back to the conditions of your former Customer Agreement (if you're already a customer) without additional fees if you tell us (and return to us in good condition any wireless phone you got from us with your new service) <strong>WITHIN 30 DAYS</strong> of accepting. You'll still be responsible through that date for the new service and any charges associated with it.</p>

<p><font size="3"><strong>Your Rights to Change or End Your Service; Termination Fees; Phone Number Portability</strong></font></p>

<p>&sect; Except as explicitly permitted by this agreement, you're agreeing to maintain service with us for your minimum term. (Periods of suspension of service don't count towards fulfillment of your minimum term.) After that, you'll become a month-to-month customer under this agreement. <strong>AN EARLY TERMINATION FEE WILL APPLY IF YOU CHOOSE TO END YOUR SERVICE BEFORE BECOMING A MONTH-TO-MONTH CUSTOMER, OR IF WE TERMINATE IT EARLY FOR GOOD CAUSE. FOR SERVICE ACTIVATED PRIOR TO 11/16/06, THE EARLY TERMINATION FEE IS $175 PER WIRELESS PHONE NUMBER. FOR SERVICE ACTIVATED ON OR AFTER 11/16/06, OR FOR LINES OF SERVICE WITH MINIMUM TERMS EXTENDED ON OR AFTER 11/16/06, THE EARLY TERMINATION FEE IS $175, WHICH WILL BE REDUCED BY $5 FOR EACH FULL MONTH TOWARD YOUR MINIMUM TERM THAT YOU COMPLETE.</strong> (The Early Termination Fee applies only to the extent permitted by law. If you buy your wireless phone from an authorized agent or third-party vendor, you should check to see if they charge a separate termination fee.) If you terminate your service as of the end of your minimum term, you won't be responsible for any remaining part of your monthly billing cycle. <strong>Otherwise, all terminations by you during a monthly billing cycle become effective on the last day of that billing cycle.</strong> You'll remain responsible for all fees and charges incurred until then and won't be entitled to any partial month credits or refunds. You may be able to take, or &quot;port,&quot; your current wireless phone number to another service provider. If you request your new service provider to port a number from us, and we receive your request from that new service provider, we'll treat it as notice from you to terminate our service for that number upon successful completion of porting. After the porting is completed, you won't be able to use our service for that number. You'll remain responsible for any Early Termination Fee, and for all fees and charges through the end of that billing cycle, just like any other termination. If you're porting a phone number to us from another company, we may not be able to provide you some services, such as 911 location services, immediately.</p>

<p><font size="3"><strong>Our Rights to Make Changes</strong></font></p>

<p>Your service is subject to our business policies, practices, and procedures, which we can change without notice. UNLESS OTHERWISE PROHIBITED BY LAW, WE CAN ALSO CHANGE PRICES AND ANY OTHER CONDITIONS IN THIS AGREEMENT AT ANY TIME BY SENDING YOU WRITTEN NOTICE PRIOR TO THE BILLING PERIOD IN WHICH THE CHANGES WOULD GO INTO EFFECT. IF YOU CHOOSE TO USE YOUR SERVICE AFTER THAT POINT, YOU'RE ACCEPTING THE CHANGES. IF THE CHANGES HAVE A MATERIAL ADVERSE EFFECT ON YOU, HOWEVER, YOU CAN END THE AFFECTED SERVICE, WITHOUT ANY EARLY TERMINATION FEE, JUST BY CALLING US WITHIN 60 DAYS AFTER WE SEND NOTICE OF THE CHANGE.</p>

<p><font size="3"><strong>Your Wireless Phone</strong></font></p>

<p>Your wireless phone is any device you use to receive our wireless voice or data service. It must comply with Federal Communications Commission regulations and be compatible with our network and your Calling Plan. Whether you buy your wireless phone from us or someone else is entirely your choice. At times we may change your wireless phone's software, applications or programming remotely and without notice. This could affect data you've stored on, the way you've programmed, or the way you use, your wireless phone. Your wireless phone may also contain software that prevents it from being used with any other company's wireless service, even if it's no longer used to receive our service.</p>

<p><font size="3"><strong>Your Wireless Phone Number and Caller ID</strong></font></p>

<p>You don't have any rights in any personal identification number, email address, or identifier we assign you (we'll tell you if we decide to change or reassign them). The same is true of your wireless phone number, except for any right you may have to port it. Your wireless phone number and name may show up when you call someone. You can block this &quot;Caller ID&quot; for most calls by dialing *67 before each call, or by ordering per-line call blocking (dialing *82 to unblock) where it's available. You can't block Caller ID to some numbers, such as toll-free numbers.</p>

<p><font size="3"><strong>How Service Works</strong></font></p>

<p>Wireless phones use radio transmissions, so we can't provide service when your wireless phone isn't in range of one of our transmission sites, or a transmission site of another company that's agreed to carry our customers' calls, or if there isn't sufficient network capacity available at that moment. Even within a coverage area, there are many factors, including customer's equipment, terrain, proximity to buildings, foliage, and weather, that may impact service.</p>

<p><font size="3"><strong>Charges and Fees We Set</strong></font></p>

<p>&sect; You agree to pay all access, usage, and other charges and fees we bill you or that the user of your wireless phone accepted, even if you weren't the user of your wireless phone and didn't authorize its use. These include Federal Universal Service, Regulatory and administrative Charges, and may also include other charges related to our governmental costs. We set these charges. They aren't taxes, aren't required by law, are kept by us in whole or in part, and the amounts and what's included are subject to change. You may have to pay fees to begin service or reconnect suspended service. Usage charges may vary depending on where, when, and how you call. You have a Home Rate and Coverage Area and a Local Calling Area (which may be different). When you call from inside a Local Calling Area to somewhere outside of it, or call from anywhere outside a Local Calling Area, there may be toll, regional calling, or long distance charges in addition to airtime (we provide or select the long distance service for calls on our network). When you make a call inside your Local Calling Area that uses a local phone company's lines (for example, a call to a typical home phone number), we may charge landline or connection fees. We charge airtime for most calls, including toll-free and operator-assisted calls. Additional features and services such as operator or directory assistance, call dialing, calling card use, Call Forwarding, data calls, automatic call delivery, Voice Mail, Text Messaging, and wireless Internet access, may have additional charges. Features such as Call Waiting, Call Forwarding, or 3-Way Calling involve multiple calls and multiple charges.</p>

<p><font size="3"><strong>Taxes, Fees, and Surcharges We Don't Set</strong></font></p>

<p>&sect; You agree to pay all taxes, fees, and surcharges set by the government. We may not always give advance notice of changes to these items. If you're tax-exempt you must give us your exemption certificates and pay for any filings we make.</p>

<p><font size="3"><strong>Roaming and Roaming Charges</strong></font></p>

<p>You're &quot;roaming&quot; whenever you make or receive a call using a transmission site outside your Home Rate and Coverage Area, or using another company's transmission site. Your wireless phone may sometimes connect to and roam on another company's network even when you're within your Home Rate and Coverage Area or Local Calling Area. There may be extra charges (including charges for long distance, tolls, or calls that don't connect) and higher rates for roaming calls, depending on your Calling Plan.</p>

<p><font size="3"><strong>Your Bill</strong></font></p>

<p>&sect; Your bill is our notice to you of your fees, charges and other important information. You should read everything in your bill. We bill usage charges after calls are made or received. We bill access fees and some other charges in advance. You can view your detailed bill online. We'll also send you a streamlined bill without call detail (or a detailed bill if you request one, subject to any applicable fee). We may charge a fee for bill reprints. If you choose Internet billing (where available), you waive any right
to paper bills or notices.</p>

<p><font size="3"><strong>How We Calculate Your Bill</strong></font></p>

<p>Your bill reflects the fees and charges in effect under your Calling Plan at the time they're incurred. You can dispute your bill, but only within 180 days of receiving it. Unless otherwise provided by state law, you must still pay any disputed charges until the dispute is resolved. Charges may vary depending on where your wireless phone is when a call starts. If a charge depends on an amount of time used, we'll round up any fraction of a minute to the next full minute. Time starts when you first press <strong>SEND</strong> or the call connects to a network on outgoing calls, and when the call connects to a network (which may be before it rings) on incoming calls. Time may end several seconds after you press <strong>END</strong> or the call otherwise disconnects. For calls made on our network, we only bill for calls that are answered (which includes calls answered by machines). Most calls you make or receive during a billing cycle are included in your bill for that cycle. Billing for airtime (including roaming) and related charges may, however, sometimes be delayed. Delayed airtime will be applied against the included airtime for the month when you actually made or received the call, even though such charges may show up on a later bill. This may result in charges higher than you'd expect in the later month.</p>

<p><font size="3"><strong>Your Rights for Dropped Calls or Interrupted Service</strong></font></p>

<p>If you get disconnected by our network from a call in your Home Rate and Coverage Area, redial. If the same number answers within 5 minutes, call us within 90 days and we'll give you a 1-minute airtime credit. If service is interrupted in your Home Rate and Coverage Area for more than 24 hours in a row due to our fault, call us within 180 days and we'll give you a credit for the period of interruption. These are your only rights for dropped calls or interrupted service.</p>

<p><font size="3"><strong>Payments, Deposits, Credit Cards, and Checks</strong></font></p>

<p>&sect; Payment is due in full as stated on your bill. IF WE DON'T RECEIVE PAYMENT IN FULL WHEN DUE, WE MAY, TO THE EXTENT PERMITTED BY THE LAW OF THE STATE OF THE BILLING ADDRESS WE HAVE ON FILE FOR YOU AT THE TIME, CHARGE YOU A LATE FEE OF UP TO 1.5 PERCENT A MONTH (18 PERCENT ANNUALLY), OR A FLAT $5 A MONTH, WHICHEVER IS GREATER, ON UNPAID BALANCES. (IF YOU CHOOSE ANOTHER COMPANY TO BILL YOU FOR OUR SERVICE [SUCH AS ANOTHER VERIZON COMPANY], LATE FEES WILL BE SET BY THAT PARTY OR BY ITS TARIFFS, WHICH MAY BE HIGHER THAN OUR LATE FEE RATE.) WE MAY ALSO CHARGE YOU FOR ANY COLLECTION AGENCY FEES THAT WE ARE CHARGED BY A COLLECTION AGENCY WE USE TO COLLECT FROM YOU IF IT IS PERMITTED BY THE LAW OF THE STATE WHERE YOU HAVE YOUR BILLING ADDRESS WHEN WE FIRST SEND YOUR ACCOUNT TO A COLLECTION AGENCY. We may require an advance deposit (or an increased deposit) from you. We'll pay simple interest on any deposit at the rate the law requires. Please retain your evidence of deposit. You agree that we can apply deposits, payments, or prepayments in any order to any amounts you owe us on any account. You can't use a deposit to pay any bill unless we agree. We refund final credit balances of less than $1 only upon request. We won't honor limiting notations you make on or with your checks. We may charge you up to $25 for any returned check, depending on applicable law.</p>

<p><font size="3"><strong>If Your Wireless Phone is Lost or Stolen</strong></font></p>

<p>If your wireless phone is lost or stolen, it is very important that you notify us immediately for your own protection, so that we can suspend your service to prevent further usage. If your bill shows charges to your phone after the loss but before you reported it, and you want a credit for those charges, we will investigate your account activity. You do not have to pay the charges you dispute while they are being investigated to determine whether the charges resulted from usage by someone not authorized to use the phone. Further, if we haven't given you a courtesy suspension of recurring monthly fees within the prior year, we'll give you one for 30 days, or until you replace or recover your wireless phone, whichever comes first. You may need to provide further information regarding the theft or loss if we ask for it.</p>

<p><font size="3"><strong>Our Rights to Limit or End Service or This Agreement</strong></font></p>

<p>You agree not to resell our service to someone else without our prior written permission. You also agree your wireless phone won't be used for any other purpose that isn't allowed by this agreement or that's illegal. You agree that you won't install, deploy, or use any regeneration equipment or similar mechanism (for example, a repeater) to originate, amplify, enhance, retransmit or regenerate a transmitted RF signal. WE CAN, WITHOUT NOTICE, LIMIT, SUSPEND, <strong>OR END</strong> YOUR SERVICE OR ANY AGREEMENT WITH YOU FOR THIS OR ANY OTHER GOOD CAUSE, including, but not limited to: (a) paying late more than once in any 12 months; (b) incurring charges larger than a required
deposit or billing limit (even if we haven't yet billed the charges); (c) harassing our employees or agents; (d) lying to us; (e) interfering with our operations; (f) breaching this agreement; (g) &quot;spamming,&quot; or other abusive messaging or calling; (h) modifying your wireless phone from its manufacturer's specifications; (i) providing credit information we can't verify; (j) using your service in a way that adversely affects our network or other customers; or (k) allowing anyone to tamper with your wireless phone number. We can also temporarily limit your service for any operational or governmental reason. If you file for bankruptcy, our rights to limit, suspend, or end your service or any agreement with you will be governed by bankruptcy law.</p>

<p><font size="3"><strong>Directory Information</strong></font></p>

<p>&sect; We don't publish directories of our customers' phone numbers. We don't provide them to third parties for listing in directories either.</p>

<p><font size="3"><strong>Your Privacy - IMPORTANT INFORMATION - PLEASE READ CAREFULLY BEFORE MAKING YOUR PURCHASE DECISION</strong></font></p>

<p>&sect; We have a duty under federal law to protect the confidentiality of information about the quantity, technical configuration, type, destination, and amount of your use of our service, together with similar information on your bills. (This doesn't include your name, address, and wireless phone number.) Except as provided in this agreement, we won't intentionally share personal information about you without your permission. <strong>WE MAY USE AND SHARE INFORMATION ABOUT YOU AND HOW YOU USE THE SERVICES: (A) SO WE CAN PROVIDE OUR GOODS OR SERVICES; (B) SO OTHERS CAN PROVIDE GOODS OR SERVICES TO US, OR TO YOU ON OUR BEHALF; (C) SO WE OR OUR AFFILIATES CAN COMMUNICATE WITH YOU ABOUT GOODS OR SERVICES THAT ANY OF US OFFER (ALTHOUGH YOU CAN CALL US ANY TIME IF YOU DON'T WANT US TO DO THIS); (D) TO PROTECT OURSELVES; OR (E) AS REQUIRED BY LAW, LEGAL PROCESS, OR EXIGENT CIRCUMSTANCES. IN ADDITION, WE MAY INCLUDE OUR OWN OR THIRD-PARTY ADVERTISING IN THE SERVICES YOU'VE PURCHASED FROM US, AND WE MAY SHARE INFORMATION ABOUT YOU WITH AFFILIATES, VENDORS AND THIRD PARTIES TO, IN ADDITION TO THE ABOVE REASONS, DELIVER RELEVANT ADVERTISING TO YOU WHILE USING THE SERVICES. WE MAY COLLECT AND TRANSMIT INFORMATION REGARDING YOUR USE OF THE SERVICES THROUGH APPLICATIONS OR OTHER SOFTWARE PRESENT ON YOUR DEVICE. IF YOU DO NOT WANT US TO COLLECT, TRANSMIT OR USE SUCH INFORMATION ABOUT YOU FOR THE ABOVE PURPOSES, YOU SHOULD NOT USE THE SERVICES; BY USING THE SERVICES, YOU EXPRESSLY AUTHORIZE US TO USE YOUR INFORMATION FOR THESE PURPOSES.</strong> Further, you've authorized us to investigate your credit history at any time and to share credit information about you with credit reporting agencies and our affiliates. If you ask, we'll tell you the name and address of any credit agency that gives us a credit report about you. It's illegal for unauthorized people to intercept your calls, but such interceptions can occur. For training or quality assurance, we may also monitor or record our calls with you.</p>

<p><font size="3"><strong>Employee Discounts</strong></font></p>

<p>You may be eligible for a discount on your monthly access fee based on an agreement between your employer and us or if you qualify under a government employee discount program. When you make changes to your account, we may require you to validate that you are still employed by your organization. You understand that by participating in an employee discount program we may release certain information relating to your service, including your name, your wireless telephone number and total monthly charge to your organization (does not apply to government employees). We may adjust your discount in accordance with your organization's agreement with us and remove your discount after your Customer Agreement expires or if you leave your employer. You agree that any change or removal of your discount, based on your employment status or your organization's agreement with us, shall not be considered to have a material adverse effect on you</p>

<p><font size="3"><strong>Disclaimer of Warranties</strong></font></p>

<p>&sect; WE MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, TO THE EXTENT PERMITTED BY APPLICABLE LAW, ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE CONCERNING YOUR SERVICE OR YOUR WIRELESS PHONE. WE CAN'T PROMISE UNINTERRUPTED OR ERROR-FREE SERVICE AND DON'T AUTHORIZE ANYONE TO MAKE ANY WARRANTIES ON OUR BEHALF. THIS DOESN'T DEPRIVE YOU OF ANY WARRANTY RIGHTS YOU MAY HAVE AGAINST ANYONE ELSE.</p>

<p><font size="3"><strong>Waivers and Limitations of Liability</strong></font></p>

<p>&sect; <strong>UNLESS THE LAW FORBIDS IT IN ANY PARTICULAR CASE, WE EACH AGREE TO LIMIT CLAIMS FOR DAMAGES OR OTHER MONETARY RELIEF AGAINST EACH OTHER TO DIRECT DAMAGES. THIS LIMITATION AND WAIVER WILL APPLY REGARDLESS OF THE THEORY OF LIABILITY, WHETHER FRAUD, MISREPRESENTATION, BREACH OF CONTRACT, PERSONAL INJURY, PRODUCTS LIABILITY, OR ANY OTHER THEORY. THIS MEANS THAT NEITHER OF US WILL SEEK ANY INDIRECT, SPECIAL, CONSEQUENTIAL, TREBLE, OR PUNITIVE DAMAGES FROM THE OTHER. THIS LIMITATION AND WAIVER ALSO APPLIES TO ANY CLAIMS YOU MAY BRING AGAINST ONE OF OUR SUPPLIERS, TO THE EXTENT THAT WE WOULD BE REQUIRED TO INDEMNIFY THE SUPPLIER FOR SUCH CLAIM.</strong> You agree we aren't liable for problems caused by you or a third party; by buildings, hills, network congestion, tunnels, weather, or other things we don't control; or by any act of God. You also agree we aren't liable for missed Voice Mails, or deletions of Voice Mails from your Voice Mailbox (if you have one), even if you've saved them. If another wireless carrier is involved in any problem (for example, while you roam), you also agree to any limitations of liability in its favor that it imposes.</p>

<p><strong>Dispute Resolution and Mandatory Arbitration</strong><br>
&sect; <strong>WE EACH AGREE TO SETTLE DISPUTES (EXCEPT CERTAIN SMALL CLAIMS) ONLY BY ARBITRATION. THERE'S NO JUDGE OR JURY IN ARBITRATION, AND REVIEW IS LIMITED, BUT AN ARBITRATOR CAN AWARD THE SAME DAMAGES AND RELIEF, AND MUST HONOR THE SAME LIMITATIONS IN THIS AGREEMENT, AS A COURT WOULD. IF AN APPLICABLE STATUTE PROVIDES FOR AN AWARD OF ATTORNEY'S FEES, AN ARBITRATOR CAN AWARD THEM TOO. WE ALSO EACH AGREE, TO THE FULLEST EXTENT PERMITTED BY LAW, THAT:</strong></p>

<p>(1) THE FEDERAL ARBITRATION ACT APPLIES TO THIS AGREEMENT. EXCEPT FOR QUALIFYING SMALL CLAIMS COURT CASES, ANY CONTROVERSY OR CLAIM ARISING OUT OF OR RELATING TO THIS AGREEMENT, OR ANY PRIOR AGREEMENT FOR WIRELESS SERVICE WITH US OR ANY OF OUR AFFILIATES OR PREDECESSORS IN INTEREST, OR ANY PRODUCT OR SERVICE PROVIDED UNDER OR IN CONNECTION WITH THIS AGREEMENT OR SUCH A PRIOR AGREEMENT, OR ANY ADVERTISING FOR SUCH PRODUCTS OR SERVICES, WILL BE SETTLED BY ONE OR MORE NEUTRAL ARBITRATORS BEFORE THE AMERICAN ARBITRATION ASSOCIATION (&quot;AAA&quot;) OR BETTER BUSINESS BUREAU (&quot;BBB&quot;). YOU CAN ALSO BRING ANY ISSUES YOU MAY HAVE TO THE ATTENTION OF FEDERAL, STATE, OR LOCAL GOVERNMENT AGENCIES AND THEY CAN, IF THE LAW ALLOWS, SEEK RELIEF AGAINST US ON YOUR BEHALF.</p>

<p>(2) FOR CLAIMS OVER $10,000, THE AAA'S WIRELESS INDUSTRY ARBITRATION (&quot;WIA&quot;) RULES WILL APPLY. FOR CLAIMS OF $10,000 OR LESS, THE COMPLAINING PARTY CAN CHOOSE EITHER THE AAA'S SUPPLEMENTARY PROCEDURES FOR CONSUMER-RELATED DISPUTES, AN INDIVIDUAL ACTION IN SMALL CLAIMS COURT, OR THE BBB'S RULES FOR BINDING ARBITRATION. EACH OF US MAY BE REQUIRED TO EXCHANGE RELEVANT EVIDENCE IN ADVANCE. IN LARGE/COMPLEX CASES UNDER THE WIA RULES, THE ARBITRATORS MUST APPLY THE FEDERAL RULES OF EVIDENCE AND THE LOSER MAY HAVE THE AWARD REVIEWED BY A PANEL OF THREE NEW ARBITRATORS.</p>

<p>(3) YOU CAN OBTAIN PROCEDURES, RULES, AND FEE INFORMATION FROM THE AAA (WWW.ADR.ORG), THE BBB (WWW.BBB.ORG), OR FROM US. <strong>THIS AGREEMENT DOESN'T PERMIT CLASS ARBITRATIONS EVEN IF THOSE PROCEDURES OR RULES WOULD.</strong> IN EXCHANGE FOR YOUR AGREEMENT TO ARBITRATE ON AN INDIVIDUAL BASIS, WE'RE PROVIDING YOU A FREE INTERNAL MEDIATION PROGRAM. MEDIATION IS A PROCESS FOR MUTUALLY RESOLVING DISPUTES. A MEDIATOR CAN HELP PARTIES REACH AGREEMENT, BUT DOESN'T DECIDE THEIR ISSUES. IN OUR MEDIATION PROGRAM, WE'LL ASSIGN SOMEONE (WHO MAY BE FROM OUR COMPANY) NOT DIRECTLY INVOLVED IN THE DISPUTE TO MEDIATE. THAT PERSON WILL HAVE ALL THE RIGHTS AND PROTECTIONS OF A MEDIATOR. NOTHING SAID IN THE MEDIATION CAN BE USED IN A LATER ARBITRATION OR LAWSUIT. CONTACT US AT <strong>VERIZONWIRELESS.COM</strong> OR THROUGH CUSTOMER SERVICE TO FIND OUT MORE.</p>

<p>(4) IF YOU REQUEST MEDIATION UNDER OUR PROGRAM, PARTICIPATE IN GOOD FAITH IN AT LEAST ONE TELEPHONIC MEDIATION SESSION, AND THE MEDIATION DOESN'T RESOLVE THE DISPUTES BETWEEN US, WE'LL PAY ANY FILING FEE LATER CHARGED YOU BY THE AAA OR BBB FOR ONE ARBITRATION OF THOSE DISPUTES. IF THAT ARBITRATION PROCEEDS, WE'LL ALSO PAY ANY FURTHER ADMINISTRATIVE AND ARBITRATOR FEES LATER CHARGED FOR IT AND (IF THE ARBITRATION AWARD IS APPEALABLE UNDER THIS AGREEMENT) ANY APPEAL TO A NEW THREE ARBITRATOR PANEL. WE MAY MAKE YOU A WRITTEN OFFER OF SETTLEMENT ANY TIME BEFORE ARBITRATION BEGINS. IF WE DO AND YOU DON'T RECOVER IN ARBITRATION MORE THAN 75% OF THE OFFERED AMOUNT, YOU AGREE TO REPAY US THE LESSER OF ANY FEES WE ADVANCED OR WHAT YOU WOULD HAVE PAID IN FEES AND COSTS IN COURT UNDER SIMILAR CIRCUMSTANCES.</p>

<p>(5) ANY ARBITRATION AWARD MADE AFTER COMPLETION OF AN ARBITRATION IS FINAL AND BINDING AND MAY BE CONFIRMED IN ANY COURT OF COMPETENT JURISDICTION. AN AWARD AND ANY JUDGMENT CONFIRMING IT ONLY APPLIES TO THE ARBITRATION IN WHICH IT WAS AWARDED AND CAN'T BE USED IN ANY OTHER CASE EXCEPT TO ENFORCE THE AWARD ITSELF.</p>

<p>(6) <strong>IF FOR SOME REASON THE PROHIBITION ON CLASS ARBITRATIONS SET FORTH IN SUBSECTION (3) ABOVE IS DEEMED UNENFORCEABLE, THEN THE AGREEMENT TO ARBITRATE WILL NOT APPLY. FURTHER, IF FOR ANY REASON A CLAIM PROCEEDS IN COURT RATHER THAN THROUGH ARBITRATION, WE EACH WAIVE ANY TRIAL BY JURY.</strong></p>

<p><font size="3"><strong>About You</strong></font></p>

<p>&sect; You represent that you're at least 18 years old and have the legal capacity to accept this agreement. If you're ordering for a company, you're representing that you're authorized to bind it, and where the context requires, &quot;you&quot; means the company.</p>

<p><font size="3"><strong>About This Agreement</strong></font></p>

<p>&sect; A waiver of any part of this agreement in one instance isn't a waiver of any part or any other instance. You can't assign this agreement or any of your rights or duties under it. We may assign all or part of this agreement or your debts to us without notice, and you agree to make all subsequent payments as instructed. NOTICES ARE CONSIDERED DELIVERED WHEN WE SEND THEM BY EMAIL OR FAX TO ANY EMAIL OR FAX NUMBER YOU'VE PROVIDED TO US, OR 3 DAYS AFTER MAILING TO THE MOST CURRENT BILLING ADDRESS WE HAVE ON FILE FOR YOU, IF BY US, OR TO THE CUSTOMER SERVICE ADDRESS ON YOUR MOST RECENT BILL, IF BY YOU. If any part of this agreement, including any part of its arbitration provisions, is held invalid, that part may be severed from this agreement. This agreement and the documents to which it refers form the entire agreement between us on their subjects. You can't rely on any other documents or statements on those subjects by any sales or service representatives, and you have no other rights with respect to service or this agreement, except as a specifically provided by law. This agreement isn't for the benefit of any third party except our parents, affiliates, subsidiaries, agents, and predecessors and successors in interest. Except to the extent we've agreed otherwise in the provisions on late fees, collection costs and arbitration, this agreement and disputes covered by it are governed by the laws of the state encompassing the area code assigned to your wireless phone number when you accepted this agreement, without regard to the conflicts of laws and rules of that state.</p>

<p>Last Updated: 05/15/07</p>
